### PR TITLE
Replaces `forcecpu` with `init_on_cpu` for clarity

### PR DESCRIPTION
**Pull request by akshaysridhar**
# Description

Replaces instances of `forcecpu` keyword with `init_on_cpu` to clarify its functionality. It only enables initialisation on CPU, and does not force the run to be on CPU. (use cases: Currently CPU initialisation needs to be enabled when using random number generators for the initial condition)

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by akshaysridhar** [comment]
bors try

**Comment by kpamnany** [comment]
Do squash before merging please.

**Comment by akshaysridhar** [comment]
bors try

**Pull request merged**
