### PR TITLE
Make CLIMA work with Revise

### PR DESCRIPTION
**Pull request by simonbyrne**
There was a weird issue with using 2 `@init` statements, so I had to merge them.

### CODE REVIEW

**Comment by jkozdon** [comment]
I had a message on slack last week from @vchuravy about Revise and that we shouldn't have the `@eval` in the `@parameter` macro. Haven't had a chance to explore this, but related to https://github.com/timholy/Revise.jl/issues/309.

**Comment by simonbyrne** [comment]
I'm looking at it at the moment: removing `eval` doesn't seem to fix it.

**Comment by simonbyrne** [comment]
This was fixed upstream. Everything now works!

**Pull request closed without merging**
