### PR TITLE
Remove more `PlanetParameters`, add more use of `CLIMAParameters`

### PR DESCRIPTION
**Pull request by charleskawczynski**
# Description

This PR does a few things:

 - Removes `Parameters/` folder (now in CLIMAParameters)
 - Removes `src/Common/Parameters/` folder (now in CLIMAParameters)
 - Bumps `CLIMAParameters` version
 - Adds `param_set` to driver arg set, so that it's always defined in the top-level driver (and we don't have duplicate `param_set`'s)
 - Add `param_set::AbstractParameterSet` to `HydrostaticBoussinesqModel`
 - Removes `PlanetParameters` from AtmosModel
 - Adds `orientation` and `param_set` to `turbulence_tensors`
 - Adds `turbulence_tensors` method wrappers
 - Adds `param_set` to `linearized_air_pressure`
 - Update docs for usage of CLIMAParameters

This PR is more involved in the model, and less so in the drivers (as that was done in previous PRs)

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/format.jl`

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by blallen** [comment]
Ocean side looks good to me! The `GyreDriver.jl`test in slurmCI should check that the physics is unchanged.

**Comment by charleskawczynski** [comment]
Thanks for checking so quickly! These PRs are tough because they easily result in conflicts so I can't really wait to merge!

**Comment by charleskawczynski** [comment]
@simonbyrne @kpamnany any idea what's going on here? This runs fine locally (and in the last slurm run). Random failure?

**Pull request merged**
