### PR TITLE
rename flx to flux to avoid confusion

### PR DESCRIPTION
**Pull request by szy21**
# Description

Rename flx to flux in the diagnostics to avoid confusion。 

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by akshaysridhar** [comment]
Thanks ! Check this file as well - https://github.com/climate-machine/CLIMA/blob/fc4f374dc5612298c93fc3cf95f257b6311045f0/src/Diagnostics/diagnostic_vars.jl#L25 these vars are the ones being accessed in `AtmosDiagnostic.jl` :D

**Comment by akshaysridhar** [comment]
bors try

**Comment by kpamnany** [comment]
And let @smarras79 know about the change! :-)

**Comment by szy21** [comment]
> I see that most of the changes are JuliaFormatter changes, but the main intent of this PR is fulfilled. I'd suggest running the diag test offline to make sure things are still in order.

I have run the diag test offline and it passed.

**Comment by akshaysridhar** [comment]
bors try

**Comment by akshaysridhar** [comment]
> > I see that most of the changes are JuliaFormatter changes, but the main intent of this PR is fulfilled. I'd suggest running the diag test offline to make sure things are still in order.
> 
> I have run the diag test offline and it passed.

OK - running test suite online now ; if it passes I'm OK to merge this.

**Comment by akshaysridhar** [comment]
bors try

**Comment by szy21** [comment]
@simonbyrne could you please take a look and let us know whether you are happy with the change? Thanks!

**Comment by szy21** [comment]
bors try

**Comment by kpamnany** [comment]
As #823 moves some of this code around and is also ready to merge, I'm going to merge this first.

**Pull request merged**
