### PR TITLE
Fix `ρ_cloud_ice` and update `gas_constant` parameters

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Two small fixes:

1. `ρ_cloud_ice` was missing a decimal place.

2. The SI units were redefined in May so that the Avogadro constant and the Boltzmann constant have exact values, giving the universal `gas_constant` the exact value 8.31446261815324 J/mol/K.

### CODE REVIEW

**Comment by tapios** [comment]
Thank you for catching the cloud ice problem (those hailstones would have hurt...), and I love the precision on the gas constant!

**Comment by simonbyrne** [comment]
@charleskawczynski this seems to have broken some tests in MoistThermo: can you look into it?

**Comment by charleskawczynski** [comment]
> @charleskawczynski this seems to have broken some tests in MoistThermo: can you look into it?

Yep, I think this is just from the increased precision. I can update the values in the tests.

**Comment by charleskawczynski** [comment]
Alright, @simonbyrne , fixed MoistThermo/SurfaceFluxes. The remaining problem looks strange and related to `MbedTLS`

**Comment by ali-ramadhan** [comment]
Ah sorry I should have realized that changing `gas_constant` would more than likely break some tests.

**Comment by tapios** [comment]
@charleskawczynski @ali-ramadhan Could you guys resolve whatever issues there are and merge this?

**Comment by charleskawczynski** [comment]
As silly as this may sound, this may be good to split into 2 PRs. The `ρ_cloud_ice` is a simple bug fix, but the `gas_constant` requires updating many coefficients in all of the integration tests (which takes some time to run/check).

I'll update this now to only fix `ρ_cloud_ice`, and we can update `gas_constant` in a separate PR.

**Comment by tapios** [comment]
Sounds good. Let’s look over these tests together when you do this. We shouldn’t have tests that fail when physical constants change.

On Nov 6, 2019, at 9:02 AM, Charles Kawczynski <notifications@github.com> wrote:

﻿

As silly as this may sound, this may be good to split into 2 PRs. The ρ_cloud_ice is a simple bug fix, but the gas_constant requires updating many coefficients in all of the integration tests (which takes some time to run/check).

I'll update this now to only fix ρ_cloud_ice, and we can update gas_constant in a separate PR.

**Pull request merged**
