### PR TITLE
Reformulate ARK timesteppers

### PR DESCRIPTION
**Pull request by mwarusz**
Seems to decrease the number of iterations of GMRES by half at the cost of storing `Nstages - 1` extra vectors. I don't have a good theory why this works, only some hand-wavy arguments. Maybe worth checking if it changes anything for https://github.com/climate-machine/CLIMA/pull/505 @jkozdon

### CODE REVIEW

**Comment by jkozdon** [comment]
> Maybe worth checking if it changes anything for #505 @jkozdon

Unfortunately it seems to make the non-Remainder tests worse and doesn't help the Remainder tests.

**Comment by jkozdon** [comment]
bors try

**Comment by simonbyrne** [comment]
What is this doing exactly? You're storing more of the past solver history between iterations?

**Comment by mwarusz** [comment]
I am formulating a linear problem for the current stage value, basically doing it in the naive way. Previously linearity was used to combine different terms under the linear operator and the linear problem solution variable was defined as a linear combination of the current and previous stages. After solving the linear problem the current stage had to be extracted. Now we solve directly for `Qstages[i]` but need to store evaluations of `L` from previous stages.

**Comment by jkozdon** [comment]
> What is this doing exactly? You're storing more of the past solver history between iterations?

To followup as well, if you look at [Giraldo, Kelly, and Constantinescu (2013)](https://doi.org/10.1137/120876034) the PR implements Equation (3.3) directly by solving for $q^{n+1}$ whereas the code its replacing is Equation (3.5) solving for $q_{tt}$.

It is the same matrix, but with a different right-hand side vector.

**Comment by simonbyrne** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by jkozdon** [comment]
Should this be merged?

**Comment by simonbyrne** [comment]
Needs to be updated for the linear solver changes.

**Comment by mwarusz** [comment]
Done

**Pull request merged**
