### PR TITLE
Fix deprecation warning caused by new package

### PR DESCRIPTION
**Pull request by kpamnany**
Also fix incorrect dependency for Pkg.

### CODE REVIEW

**Comment by vchuravy** [comment]
bors try

**Comment by kpamnany** [comment]
bors try

**Comment by kpamnany** [comment]
Ha. I manually ran SlurmCI and the status it uploaded was caught above. Interestingly, everything passed [except Kessler again](https://gist.github.com/93161b4574c63a11dc2e1243ea2fcda2), which just doesn't seem to like newer versions of CUDA*. @vchuravy: see the launch error there.

**Comment by kpamnany** [comment]
Loading the `netcdf` module [didn't help](https://gist.github.com/climabot/bee84952cf49ba4df9c031832116d805#file-out_8772688). Also `ldconfig` is not found? 😖

**Comment by vchuravy** [comment]
Let's debug that failure next week together. Looks like we have to get creative.

**Comment by kpamnany** [comment]
bors try

**Comment by kpamnany** [comment]
bors try

**Comment by kpamnany** [comment]
I have verified that Kessler passes when I switch to `CUDAnative#master` and fails again with `CUDAnative@2.10.2`. @vchuravy: can we get a `CUDAnative` release? :-)

**Comment by vchuravy** [comment]
@mwarusz and I have been staring at this. Hopefully we will figure that out.

**Comment by kpamnany** [comment]
bors try

**Comment by kpamnany** [comment]
bors try-

**Pull request merged**
