### PR TITLE
Remove Canary.jl dependency

### PR DESCRIPTION
**Pull request by simonbyrne**
This copies the necessary files from Canary.jl into the main CLIMA repo, which should make it easier to maintain.

### CODE REVIEW

**Comment by simonbyrne** [comment]
@lcw I'm just using the GaussQuadrature package, instead of copying the `GaussQuadrature` directory from Canary. Is that okay?

**Comment by lcw** [comment]
Simon Byrne <notifications@github.com> writes:

> @lcw I'm just using the GaussQuadrature package, instead of copying
> the `GaussQuadrature` directory from Canary. Is that okay?

That should be fine.

**Comment by simonbyrne** [comment]
Great. I just need to copy over the tests as well.

**Pull request merged**
