### PR TITLE
MPIStateArrays: add generic mapreduce support

### PR DESCRIPTION
**Pull request by simonbyrne**
cc: @blallen @jkozdon

### CODE REVIEW

**Comment by blallen** [comment]
Thanks for doing this @simonbyrne!

I tried to use this in `test_divergence_free.jl` from #535 and got two different errors pointing at line 60 of MPIStateArrays.jl when running on the GPU. Everything worked perfectly fine on the CPU.

The first time was `ERROR: LoadError: Type Array does not have a definite size.` inside of the `init_ode_state()` call and the second time was `ERROR: LoadError: MethodError: no method matching similar(::Type{CuArray}, ::Type{Float64}, ::Int64, ::Int64, ::Int64)` inside of a `create_auxstate()` within the `OceanDGModel()` call. 

Can you take a look at this? I'll push my latest changes to bla/HydrostaticBoussinesqModel on the main repo so you can just check out that branch and run.

**Comment by blallen** [comment]
> Thanks for doing this @simonbyrne!
> 
> I tried to use this in `test_divergence_free.jl` from #535 and got two different errors pointing at line 60 of MPIStateArrays.jl when running on the GPU. Everything worked perfectly fine on the CPU.
> 
> The first time was `ERROR: LoadError: Type Array does not have a definite size.` inside of the `init_ode_state()` call and the second time was `ERROR: LoadError: MethodError: no method matching similar(::Type{CuArray}, ::Type{Float64}, ::Int64, ::Int64, ::Int64)` inside of a `create_auxstate()` within the `OceanDGModel()` call.
> 
> Can you take a look at this? I'll push my latest changes to bla/HydrostaticBoussinesqModel on the main repo so you can just check out that branch and run.

Actually, I rolled back this commit to do some tests and am still getting the same error, so I think it might be related to the CPU initialization for GPU running instead. Currently following the stack trace for the first error and trying to understand what's happening.

**Comment by blallen** [comment]
Since #560 fixed the issue mentioned above, I tried to run the test again and now I get an error within the mapreduce function.  The stacktrace is below and line numbers refer to the latest version of the files in #535 .

```
ERROR: LoadError: scalar getindex is disallowed
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] assertscalar(::String) at /home/blallen/.julia/packages/GPUArrays/m9bSO/src/indexing.jl:14
 [3] getindex at /home/blallen/.julia/packages/GPUArrays/m9bSO/src/indexing.jl:54 [inlined]
 [4] _getindex at ./abstractarray.jl:1004 [inlined]
 [5] getindex at ./abstractarray.jl:981 [inlined]
 [6] getindex at ./subarray.jl:230 [inlined]
 [7] _getindex at ./abstractarray.jl:1021 [inlined]
 [8] getindex at ./abstractarray.jl:981 [inlined]
 [9] iterate at ./abstractarray.jl:914 [inlined]
 [10] iterate at ./abstractarray.jl:912 [inlined]
 [11] mapfoldl_impl(::Function, ::Function, ::NamedTuple{(),Tuple{}}, ::SubArray{Float64,3,CuArray{Float64,3},Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}},false}) at ./reduce.jl:55
 [12] #mapfoldl#188 at ./reduce.jl:72 [inlined]
 [13] mapfoldl at ./reduce.jl:72 [inlined]
 [14] _mapreduce at ./reduce.jl:330 [inlined]
 [15] _mapreduce_dim at ./reducedim.jl:312 [inlined]
 [16] #mapreduce#555 at ./reducedim.jl:307 [inlined]
 [17] mapreduce at ./reducedim.jl:307 [inlined]
 [18] reducedim_init(::Function, ::typeof(max), ::CuArray{Float64,3}, ::Tuple{Int64,Int64}) at ./reducedim.jl:145
 [19] #mapreduce#21 at ./reducedim.jl:317 [inlined]
 [20] #mapreduce at ./none:0 [inlined]
 [21] _maximum at ./reducedim.jl:679 [inlined]
 [22] _maximum at ./reducedim.jl:678 [inlined]
 [23] #maximum#562 at ./reducedim.jl:652 [inlined]
 [24] #maximum at ./none:0 [inlined]
 [25] (::getfield(Main, Symbol("##3#4")){HydrostaticBoussinesqModel{HomogeneousSimpleBox{Float64},Float64},MPIStateArray{Float64,CuArray{Float64,3},CuArray{Int64,1},CuArray{Float64,3},CuArray{Float64,2}},Base.RefValue{DateTime}})(::Bool) at /home/blallen/CLIMA/test/Ocean/Hydrostatic_Boussinesq/test_divergence_free.jl:172
 [26] (::getfield(Main, Symbol("##3#4")){HydrostaticBoussinesqModel{HomogeneousSimpleBox{Float64},Float64},MPIStateArray{Float64,CuArray{Float64,3},CuArray{Int64,1},CuArray{Float64,3},CuArray{Float64,2}},Base.RefValue{DateTime}})() at /home/blallen/CLIMA/test/Ocean/Hydrostatic_Boussinesq/test_divergence_free.jl:168
 [27] (::CLIMA.GenericCallbacks.EveryXWallTimeSeconds)(::Bool) at /home/blallen/CLIMA/src/ODESolvers/GenericCallbacks.jl:48
 [28] EveryXWallTimeSeconds at /home/blallen/CLIMA/src/ODESolvers/GenericCallbacks.jl:29 [inlined]
 [29] #solve!#1(::Int64, ::Bool, ::Int64, ::Tuple{CLIMA.GenericCallbacks.EveryXWallTimeSeconds}, ::typeof(solve!), ::MPIStateArray{Float64,CuArray{Float64,3},CuArray{Int64,1},CuArray{Float64,3},CuArray{Float64,2}}, ::LowStorageRungeKutta2N{Float64,Float64,MPIStateArray{Float64,CuArray{Float64,3},CuArray{Int64,1},CuArray{Float64,3},CuArray{Float64,2}},14}, ::Nothing) at /home/blallen/CLIMA/src/ODESolvers/ODESolvers.jl:80
 [30] (::getfield(CLIMA.ODESolvers, Symbol("#kw##solve!")))(::NamedTuple{(:timeend, :callbacks),Tuple{Int64,Tuple{CLIMA.GenericCallbacks.EveryXWallTimeSeconds}}}, ::typeof(solve!), ::MPIStateArray{Float64,CuArray{Float64,3},CuArray{Int64,1},CuArray{Float64,3},CuArray{Float64,2}}, ::LowStorageRungeKutta2N{Float64,Float64,MPIStateArray{Float64,CuArray{Float64,3},CuArray{Int64,1},CuArray{Float64,3},CuArray{Float64,2}},14}, ::Nothing) at ./none:0
 [31] top-level scope at /home/blallen/CLIMA/test/Ocean/Hydrostatic_Boussinesq/test_divergence_free.jl:200
 [32] include at ./boot.jl:328 [inlined]
 [33] include_relative(::Module, ::String) at ./loading.jl:1094
 [34] include(::Module, ::String) at ./Base.jl:31
 [35] exec_options(::Base.JLOptions) at ./client.jl:295
 [36] _start() at ./client.jl:464
in expression starting at /home/blallen/CLIMA/test/Ocean/Hydrostatic_Boussinesq/test_divergence_free.jl:118
```

**Comment by simonbyrne** [comment]
Okay, I had to temper my ambitions here: due to the differences in how reductions in how Arrays and CuArrays are implemented, I had to special case it so that only summation, minimum and maximum will reliably work on both.

**Pull request merged**
