### PR TITLE
added LocalGeometry object to query length scale and coordinates

### PR DESCRIPTION
**Pull request by simonbyrne**
Thoughts welcome.

### CODE REVIEW

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
I gave it the name before putting `coord` in there, so i realise it isn't really "local" any more. Any suggestions for a better name?

We might also be able to use this to capture the gravity potential as well (though then the name is even less appropriate)

**Comment by charleskawczynski** [comment]
> I gave it the name before putting `coord` in there, so i realise it isn't really "local" any more. Any suggestions for a better name?

How is it not local?

**Comment by simonbyrne** [comment]
it's still local in the sense that it pertains to the particular node, but not in the differential geometry sense (because it stores the global coordinates).

**Comment by charleskawczynski** [comment]
Ahh, we need a naming convention for our coordinate systems to distinguish these differences.

**Comment by charleskawczynski** [comment]
How about

`GlobalCoord` for `x1,x2,x3` and
`ElemCoord` for `ξ1, ξ2, ξ3`

**Comment by simonbyrne** [comment]
`CartesianCoord`?

**Comment by simonbyrne** [comment]
bors try

**Pull request merged**
