### PR TITLE
Bug fix in atmos diagnostic

### PR DESCRIPTION
**Pull request by jkozdon**
# Description

I believe that this correction is needed based on #961

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/format.jl`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by jkozdon** [comment]
@kpamnany: I found this when rebasing one of my branches on #961. Not sure how to test it though.

**Comment by kpamnany** [comment]
Yes, we saw this broke because bors merged this PR together with the one that changed the names. :(  Thanks for this fix.

**Comment by kpamnany** [comment]
I'm enabling running all the diagnostics in different experiments on Slurm CI in another PR, for testing purposes.

**Comment by kpamnany** [comment]
This fix is included in #1028.

**Pull request closed without merging**
