### PR TITLE
Changes to ease use of ocean_gyre.jl

### PR DESCRIPTION
**Pull request by blallen**
# Description

A clear and concise description of the code with usage.

Exposes vtk and diagnostics saving methods. Reduces default courant number to somewhere near stable and shows how to manually set the time step. Better information from the automatic timestep calculation. Also applied the JuliaFormattere to these two files.

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/format.jl`

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by charleskawczynski** [comment]
> I also suggest using
> 
> ```julia
> using CLIMA.PlanetParameters: grav
> ```
> 
> to clarify where the variable `grav` arises.

Just a heads up, `grav` will be changing to a function in #868. So it'll be easier to find out where it's defined.

**Comment by jm-c** [comment]
I would suggest to change, in src/Ocean/HydrostaticBoussinesq/SimpleBoxProblem.jl
in function ocean_init_state,  to replace (line 103):
  Q.u = @SVector [rand(),rand()]
with:
  Q.u = @SVector [0,0]
+ comments above regarding initial state.
 I am not sure it should go into this PR, but it's a simple (1 line) change that would go
into the right direction.

**Comment by jm-c** [comment]
@blallen I think you can ignore my previous comment: The rand-noise initial velocity is only used
for HomogeneousBox (to test divergence-free ?) and not in the ocean_gyre set-up.

**Comment by blallen** [comment]
@charleskawczynski @akshaysridhar @bischtob @kpamnany has anyone tested how long the `gcm_driver_test.jl` takes? It seems that the Linux azure test is hanging on this right now:

https://dev.azure.com/climate-machine/CLIMA/_build/results?buildId=2250&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e

**Comment by charleskawczynski** [comment]
On one of the recent Azure builds, it looks like [3888.752310 seconds](https://dev.azure.com/climate-machine/CLIMA/_build/results?buildId=2249&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=74b99ac4-969e-5d5f-3589-394e967bbd0f).

**Comment by blallen** [comment]
> On one of the recent Azure builds, it looks like [3888.752310 seconds](https://dev.azure.com/climate-machine/CLIMA/_build/results?buildId=2249&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=74b99ac4-969e-5d5f-3589-394e967bbd0f).

Ended up taking 4067.67884 seconds for this one. But the actual timestepping took less than two minutes. Do we know what's taking so long?

**Comment by charleskawczynski** [comment]
> But the actual timestepping took less than two minutes.

But, in the link I sent
```
┌ Info: Update
│ simtime =   600.00 /  1800.00
│ runtime = 01:03:28
└ norm(Q) = 9.5073453551765578e+13
```
and this is during "Update".

**Pull request merged**
