### PR TITLE
Update advection diffusion test to Julia 1.3

### PR DESCRIPTION
**Pull request by jkozdon**
Update advection diffusion to use Julia 1.3 results; Slurm CI upgraded to with climate-machine/slurmci#11

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Thank you!

**Comment by blallen** [comment]
should we wait for this to be merged before we add the commit to other outstanding PRs?

**Comment by blallen** [comment]
just pushed a commit where I cut the endtime for `test_divergence_free.jl` in half. Hopefully that will prevent it from timing out again

**Comment by charleskawczynski** [comment]
> just pushed a commit where I cut the endtime for test_divergence_free.jl in half. Hopefully that will prevent it from timing out again

Won't that break the results being checked?

**Comment by blallen** [comment]
> > just pushed a commit where I cut the endtime for test_divergence_free.jl in half. Hopefully that will prevent it from timing out again
> 
> Won't that break the results being checked?

it's just checking that a constant scalar tracer stays constant. the test doesn't depend on the exact run time because it's just checking that min(θ) = max(θ) when θ=20 everywhere at the start

**Comment by jkozdon** [comment]
> just pushed a commit where I cut the endtime for `test_divergence_free.jl` in half. Hopefully that will prevent it from timing out again

Weird that this has started to time out. Did something else change on the Slurm CI? Or is Julia 1.3 slower for CLIMA some how?

**Pull request merged**
