### PR TITLE
Try setting Azure PR trigger

### PR DESCRIPTION
**Pull request by simonbyrne**
# Description

Attempt to fix issue where Azure CI is not building on PRs

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by simonbyrne** [comment]
Disabling codecov reduces linux tests from 2h 35m 30s to 59 mins

**Comment by blallen** [comment]
Can we run the codecov check as a separate job? So have linux, macOS, windows, and codecov jobs launched on Azure?

**Comment by kpamnany** [comment]
> Can we run the codecov check as a separate job? So have linux, macOS, windows, and codecov jobs launched on Azure?

Probably, but what's the advantage? It has to run the entire test suite to determine coverage anyway.

**Comment by blallen** [comment]
> Probably, but what's the advantage? It has to run the entire test suite to determine coverage anyway.

Ah, not much at that point. But you'd know your code is bug-free an hour earlier, since you can see the status of individual Azure jobs.

**Comment by jkozdon** [comment]
> Ah, not much at that point. But you'd know your code is bug-free an hour earlier, since you can see the status of individual Azure jobs.

Running the tests that run on Azure locally is fairly easy if you just want to see if there is a good chance Azure will pass:

```
julia --project=@. -e 'using Pkg; Pkg.test()'
```

At one point we had scripts to allow running slurm tests locally as well, but those went away when the slurm system was rewritten.

**Comment by kpamnany** [comment]
> At one point we had scripts to allow running slurm tests locally as well, but those went away when the slurm system was rewritten.

It shoud be pretty straightforward to add this capability back into SlurmCI. I'll open an issue there to remind myself to get to it.

**Pull request closed without merging**
