### PR TITLE
Fix type in ConstantViscosityWithDivergence

### PR DESCRIPTION
**Pull request by jkozdon**
Remove `Float64` hard coding from `ConstantViscosityWithDivergence`

### CODE REVIEW

**Comment by jkozdon** [comment]
Even if we do not want to do this, we should at least change https://github.com/climate-machine/CLIMA/blob/e7033ea4f4430dad1f088ee0575f39f9c20d255f/src/Atmos/Model/turbulence.jl#L31-L33

to
```julia
 struct ConstantViscosityWithDivergence{T} <: TurbulenceClosure 
   ρν::T
 end
```

**Comment by simonbyrne** [comment]
I'd be fine with the latter proposal. I'd only do the former if we were sure there was a clear benefit (also we are unlikely to be using this for production, it is mainly for testing).

**Comment by jkozdon** [comment]
> I'd be fine with the latter proposal.

Changed.

**Pull request merged**
