### PR TITLE
New approach to doing integrals

### PR DESCRIPTION
**Pull request by jkozdon**
Allows the user to say where integrals are stored and what integrals are reversed

### CODE REVIEW

**Comment by jkozdon** [comment]
@blallen This might address some of your concerns. If you like this approach, we'd need to fix all the other codes to use this format (right now I just did the integral test).

**Comment by jkozdon** [comment]
Also need to test on the GPU

**Comment by blallen** [comment]
@jkozdon I like this approach. I will test it out in the HydrostaticBoussinesqModel tomorrow.

**Comment by jkozdon** [comment]
@blallen Just forced pushed some commits (GPU was broken since you cannot create views into shared memory). Also updated file `integral_test_sphere`

**Comment by blallen** [comment]
@jkozdon is the atmos model integral call the only one left that we need to update? I think there are just the two integral tests, the ocean model, and atmos model that use integrals right now and everything else has the `_old` suffix

**Comment by jkozdon** [comment]
@jkozdon<https://github.com/jkozdon> is the atmos model integral call the only one left that we need to update? I think there are just the two integral tests, the ocean model, and atmos model that use integrals right now and everything else has the _old suffix

I believe that this is correct.

**Comment by blallen** [comment]
bors try

**Comment by blallen** [comment]
@jkozdon , time to merge this? is there anyone else we should ask to look at it?

**Comment by jkozdon** [comment]
bor r+

**Comment by jkozdon** [comment]
@simonbyrne Sorry, rebased to cleanup the commits

**Pull request merged**
