### PR TITLE
Cleaning up Ocean Model files and adding documentation

### PR DESCRIPTION
**Pull request by blallen**
Restructured and reorganized HydrostaticBoussinesqModel.jl to improve understanding. Factored out the LinearHBModel into its own file and boundary conditions into OceanBoundaryConditions.jl. Will be adding comments for the other three files shortly.

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
I can take a closer look but just a quick note: Not sure if Documenter.jl will care but I think Julia docstrings convention want the function signature indented but not the docstring itself: https://docs.julialang.org/en/v1/manual/documentation/index.html (they also have some good recommendations)

For example,
```julia
"""
    vars_state(::HBModel)
    prognostic variables evolved forward in time
    u = (u,v) = (zonal velocity, meridional velocity)
    η = sea surface height
    θ = temperature
"""
```
should be
```julia
"""
    vars_state(::HBModel)

prognostic variables evolved forward in time
u = (u,v) = (zonal velocity, meridional velocity)
η = sea surface height
θ = temperature
"""
```

**Comment by charleskawczynski** [comment]
It's easy to test in the REPL, too!

**Comment by blallen** [comment]
@christophernhill @ali-ramadhan all the comments are in. does this help you understand what is going on?

**Comment by blallen** [comment]
bors try

**Comment by blallen** [comment]
bors try

**Pull request merged**
