### PR TITLE
Remove old drivers

### LINKED ISSUE #616: Move Dycoms radiation specs to driver
Including `DYCOMSRadiation`

### PR DESCRIPTION
**Pull request by kpamnany**
Final version of #592 and #672. Removes old versions of DYCOMS and Held-Suarez now that the versions in `experiments/` have been validated. Also:
1. Move `DYCOMSRadiation` and `DYCOMS_BC` into driver
2. Migrate Rayleigh-Benard test + b.c. from `test/DGmethods` into driver-config
   and into `examples/Atmos` with default-override comments
3. Remove unneeded models in the diagnostics test case
4. Add `ode_dt` keyword parameter in `CLIMA.setup_solver()` to allow
   overriding `dt` computation
5. Export turbulent tensor function
6. Move RTB into driver-config

@smarras79 and @thomasgibson: as we're removing old drivers that you used to use in this PR, please post to confirm that you're okay with it.

Closes #616.

### CODE REVIEW

**Comment by kpamnany** [comment]
bors try

**Comment by smarras79** [comment]
@kpamnany thanks for this PR. Let me run a test off the current master and get back to you if I see that things are all fine (at least w.r.t. dycoms)

**Pull request merged**
