### PR TITLE
Add init_aux args, needed for Courant calcs

### PR DESCRIPTION
**Pull request by charleskawczynski**
Adds `Dx,Dy` (`min_node_distance`), broken off from #610

### CODE REVIEW

**Comment by simonbyrne** [comment]
Where are these actually used? In #610 these variables are only used at the driver level, and not actually used inside `init_aux!`.

**Comment by simonbyrne** [comment]
@smarras79?

**Comment by charleskawczynski** [comment]
They’re used in the Courant module, which is in another small PR

**Comment by simonbyrne** [comment]
#612? `gather_Courant` is called at the drive level, not inside `init_aux`

**Comment by charleskawczynski** [comment]
Yeah, I think you’re right, I’ll double check tomorrow and close if it’s not used.

**Comment by charleskawczynski** [comment]
Yeah, this is unused. Closing.

**Pull request closed without merging**
