### PR TITLE
Make MPIStateArray Vars aware

### PR DESCRIPTION
**Pull request by jkozdon**
Allows the users to access the subarray using Vars like notation

Co-authored-by: blallen <ballen@mit.edu>
Co-authored-by: Jean-Michel Campin <jmc@mit.edu>
Co-authored-by: leios <jrs.schloss@gmail.com>

### CODE REVIEW

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try-

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try

**Comment by blallen** [comment]
@jkozdon is there anything we are waiting on before merging this?

**Comment by jkozdon** [comment]
The big problem I know is that right now vars within vars isn't properly supported, so you cannot do `Q.moisture.qt`, but only `Q.moisture`.

**Comment by jkozdon** [comment]
I should also say, to support the vars within vars you need something like what I am playing with on my branch `jek/VarsArrays` ([current commit link](https://github.com/climate-machine/CLIMA/tree/d677ebd15b509a2e665be1c447e9992b96f3d934)), so that `Q.moisture` returns a view that is vars aware.

**Comment by blallen** [comment]
Ah okay, makes sense. How long do you think that will take?

We'll need it to merge in the split-explicit ocean, but there's no rush since I've just barely gotten the new timestepper to initialize properly.

**Comment by jkozdon** [comment]
> Ah okay, makes sense. How long do you think that will take?

@simonbyrne: What are your thoughts on this interface?

> We'll need it to merge in the split-explicit ocean, but there's no rush since I've just barely gotten the new timestepper to initialize properly.

OK. I would recommend trying to debug things with a simpler ODE problem (such as the [RobertsSarsharSandu2018arxiv](https://github.com/climate-machine/CLIMA/blob/7956017fb59bd1e566716c5d7f8d2816df57d77b/test/ODESolvers/ode_tests.jl#L234-L280) test problem in the ODE test suite)

**Comment by simonbyrne** [comment]
Thanks @jkozdon.

If we're going to move to a "Field" object (#690), maybe it would make sense to start that transition now by just building a shallow wrapper on top of it?

I'm looking into the recursive vars stuff as well.

**Comment by blallen** [comment]
@jkozdon if you can figure out an easy way to squash the last two commits that would be great, @leios and I have reached the limits of our git-fu

**Comment by jkozdon** [comment]
Sure. Just give me a couple minutes.

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
OK. History should be pretty clean now. Took a bit more finagling than anticipated, but got it done.

**Comment by blallen** [comment]
Thanks Jeremy!!

**Comment by kpamnany** [comment]
Allowing PRs which reduce CI time to go ahead. Will r+ after those go in.

**Comment by charleskawczynski** [comment]
@kpamnany doesn't this need to be rebased first? `varsindex` was merged in #876.

**Comment by jkozdon** [comment]
> doesn't this need to be rebased first? `varsindex` was merged in #876.

@charleskawczynski You are right, will fix and push back out.

**Comment by jkozdon** [comment]
Thanks @charleskawczynski for catching this duplication

**Pull request merged**
