### PR TITLE
Added soundings directory containing sounding files

### PR DESCRIPTION
**Pull request by smarras79**
* CLIMA/src/InputOutput/soundings
* CLIMA/src/InputOutput/soundings/sounding_gabersek.dat

These files are small ASCII files necessary to initialize certain test cases such as Squall_line.

This PR should solve the issue arose by @jkozdon  in PR #405 
NOTICE: Adjust the path to sounding_gabersek.dat from the squall line driver.

### CODE REVIEW

**Comment by jkozdon** [comment]
Maybe just add this to PR #405?

**Comment by jkozdon** [comment]
Just thinking since nothing in master uses this right now, we may want to hold off adding it to the repo until it is used and tested.

**Comment by charleskawczynski** [comment]
@smarras can we close this?

**Comment by charleskawczynski** [comment]
`sounding_gabersek` data is being added to #821

**Pull request closed without merging**
