### PR TITLE
Move coverage CI  to GitHub Actions

### PR DESCRIPTION
**Pull request by charleskawczynski**
# Description

This PR:
 - [x] Adds a coverage GitHub Actions CI (GitHub hosted)
 - [x] Removes coverage from the azure pipeline YML

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/format.jl`

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by kpamnany** [comment]
Where does the coverage information get posted, if it's not to a PR thread?

**Comment by vchuravy** [comment]
> Where does the coverage information get posted, if it's not to a PR thread?

https://codecov.io/gh/climate-machine/CLIMA

One thing we could do is to actually run it on PRs but to not gate bors on it.

**Comment by charleskawczynski** [comment]
> One thing we could do is to actually run it on PRs but to not gate bors on it.

True, but the CI will still get backlogged by coverage runs unless we trigger them under a different azure organization (which we could do). The other problem with that is that triggering CI with GHA requires [Personal Access Tokens](https://github.com/Azure/pipelines#sample-workflow) which seem to have a maximum [90-day lifetime](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page).

**Comment by vchuravy** [comment]
> True, but the CI will still get backlogged by coverage runs unless we trigger them under a different azure organization (which we could do). 

That should be alleviated by running on Github actions?

> The other problem with that is that triggering CI with GHA requires Personal Access Tokens which seem to have a maximum 90-day lifetime.

Why do we need a PAT? It should be triggered from the PR?

**Comment by charleskawczynski** [comment]
> Why do we need a PAT? It should be triggered from the PR?

Ah, sorry I didn't specify, that's if we want the CI to still run on Azure. We could run coverage no problem with GitHub hosted (by cron or PR)

> That should be alleviated by running on Github actions?

Yes, if we use GitHub hosted. No if we use Azure hosted

**Comment by charleskawczynski** [comment]
Should we just make coverage run on GH resources every PR? That'd be pretty simple I think.

**Comment by charleskawczynski** [comment]
Oh, the only potential problem with that is if we're timing out. But I guess we're moving more things out of `runtests.jl` anyway, so I think this is a reasonable long term solution.

**Comment by charleskawczynski** [comment]
I'll update the cron jobs to be on each PR, since what I have right now is using GH hosted anyway.

**Comment by charleskawczynski** [comment]
@kpamnany @vchuravy looks like this is running, feel free to merge if it looks okay! Hopefully, this will speed up Azure since Azure will no longer be running with coverage!

**Comment by simonbyrne** [comment]
I think a nightly cron on master is fine for now.

**Comment by vchuravy** [comment]
> Hmm, looks like something broke with KernelAbstractions, cc: @vchuravy

Seems like you are running with Julia 1.4, best to use
https://github.com/julia-actions/setup-julia to choose the right version of Julia.

**Pull request merged**
