### PR TITLE
removing old kernels

### PR DESCRIPTION
**Pull request by leios**
Can we just remove these?

@vchuravy Forced me to do this and takes all responsibility

### CODE REVIEW

**Comment by leios** [comment]
bors try

**Comment by lcw** [comment]
I think we were waiting for https://github.com/climate-machine/CLIMA/issues/491 before removing these.

**Comment by leios** [comment]
@lcw Thanks for that.

I didn't know this was already somewhat documented. It seems like there are also a few microphysics examples that rely on these old kernels.

Would anyone mind if I attacked that issue in this PR? It's low-priority, so maybe next week.

**Comment by lcw** [comment]
@leios it would be great if you want to attack #491.  Let me know if you run into issues, I would be happy to help.

**Comment by bischtob** [comment]
The comments/documentation in DGMethods_old is outstanding. Can we make sure the wisdom carries over to the updated DGMethods?

**Comment by jkozdon** [comment]
> The comments/documentation in DGMethods_old is outstanding. Can we make sure the wisdom carries over to the updated DGMethods?

Thanks. We did spend a bit of time on this initially, but some of that got lost in the transition to the current framework.

We initially modeled our docs on

- https://github.com/JuliaFEM/JuliaFEM.jl
- https://dealii.org/current/doxygen/deal.II/Tutorial.html

But this never really got fully flushed out and never transitioned to the newest framework.

**Comment by charleskawczynski** [comment]
@leios We need to also remove these files from being included in `src/CLIMA.jl`

**Pull request closed without merging**
