### PR TITLE
Fix integration of pkin in ocean model

### PR DESCRIPTION
**Pull request by jkozdon**
#727 lacked the integration of pkin in the ocean model. This fixes that.

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by jkozdon** [comment]
@jm-c Can you check and confirm this fixes the problems you were seeing.

**Comment by jm-c** [comment]
I will take a look this evening/tonight and will let you know. Thanks.

**Comment by jm-c** [comment]
I've tried it and it works ! Back to normal ! Thanks

**Pull request merged**
