### PR TITLE
add TVDMIS methods

### PR DESCRIPTION
**Pull request by simonbyrne**
TVDMISB works, however beta values for TVDMISA appear to be incorrect. Awaiting input from the author.

### CODE REVIEW

**Comment by simonbyrne** [comment]
TVDMISA values have been updated.

bors r+

**Comment by jkozdon** [comment]
> TVDMISB works, however beta values for TVDMISA appear to be incorrect

Was these an error in the paper? If so, could you add a comment for what needs to be corrected? (As someone who has had to track down inconsistencies in coefficients before, I think this would be useful to others to have noted somewhere)

**Comment by simonbyrne** [comment]
> Was these an error in the paper? If so, could you add a comment for what needs to be corrected? (As someone who has had to track down inconsistencies in coefficients before, I think this would be useful to others to have noted somewhere)

No: the error was in the initial code sample provided by the author. The paper didn't have the full coefficients (I believe the rest of them should have been computable from the details given, but I didn't quite understand how they were arrived at).

**Pull request merged**
