### PR TITLE
Move conservation/sphere test to the new framework

### PR DESCRIPTION
**Pull request by mwarusz**
Partially addresses #491 

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
Seems to work as long as you use smaller tolerance. I have enabled it.

**Comment by jkozdon** [comment]
@mwarusz Is this ready to go? Do you want me to fix the merge conflicts?

**Pull request merged**
