### PR TITLE
Add hyperdiffusion

### PR DESCRIPTION
**Pull request by mwarusz**
TODO list:
- [x] allow selective application of hyperdiffusion to specific variables
- [x] modify new kernels and numerical fluxes similarly as in  #631 
- [ ] figure out a boundary condition interface consistent with #630 and #656 and add a test with non-periodic boundary conditions
- [ ] simplify kernels and do some benchmarking
- [x] update docs

### CODE REVIEW

**Comment by mwarusz** [comment]
bors try

**Comment by bischtob** [comment]
Quick question for clarification from my side here for @fxgiraldo, @mwarusz, @akshaysridhar: Since we need hyperdiffusion in the horizontal direction on the sphere in order to stabilize the GCM it seems that boundary condititions should be no problem for the GCM setup? I am asking because this is the most immediate application of the hyperdiffusion component in the atmosphere model.

**Comment by fxgiraldo** [comment]
> Quick question for clarification from my side here for @fxgiraldo, @mwarusz, @akshaysridhar: Since we need hyperdiffusion in the horizontal direction on the sphere in order to stabilize the GCM it seems that boundary condititions should be no problem for the GCM setup? I am asking because this is the most immediate application of the hyperdiffusion component in the atmosphere model.

@bischtob @akshaysridhar , spoke to @mwarusz and we agree.  Since we can apply hyperdiffusion along the horizontal direction then for the sphere, BCs should not be an issue.

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
@akshaysridhar @bischtob 

I updated this branch to the current master and added a way to make diffusion and hyperdiffusion act only in the horizontal on the sphere. You simply need to pass a keyword argument ```diffusion_direction=HorizontalDirection()``` to the `DGModel` constructor.

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
As discussed, the boundary conditions will be handled in another PR, since this one is already quite big. I think this is ready to go in. @akshaysridhar @bischtob

**Comment by mwarusz** [comment]
bors try

**Comment by akshaysridhar** [comment]
> As discussed, the boundary conditions will be handled in another PR, since this one is already quite big. I think this is ready to go in. @akshaysridhar @bischtob 
Awesome :D ! 
#728 is linked to this, @mwarusz ; handles the `AtmosModel.jl`/ `hyperdiffusion.jl` facing side, once this is merged I can update that branch with some sensible defaults (and working demonstrations with the current `experiments`).

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Pull request merged**
