### PR TITLE
Remove `PlanetParameters`, for good!

### LINKED ISSUE #957: Migrate to CLIMAParameters.jl
# Description

To track this for our first release:

 - [ ] Remove `CLIMA.PlanetParameters` (and move to `CLIMAParameters.jl`)
 - [ ] Remove `CLIMA.MicrophysicsParameters` (and move to `CLIMAParameters.jl`)
 - [ ] Remove `CLIMA.ParametersType`

Relevant PRs:

- #962, #952, #920, #935, #903, #901, #893, #875, #802, #726

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [x] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [x] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

### PR DESCRIPTION
**Pull request by charleskawczynski**
# Description

Replaces

 - `PlanetParameters`
 - `MicrophysicsParameters`
 - `SubgridScaleParameters`
 - `ParametersType`

with `CLIMAParameters`. Also removes the corresponding modules and tests. This PR also reorders `param_set` to be the first argument of every moist-thermo and microphysics function (since it's not required and doesn't make sense to follow the frequent optional argument `PhasePartition`)

closes #957

This also adds CLIMAParameters to the docs environment.

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/format.jl`

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by akshaysridhar** [comment]
Does #861 interfere with this @charleskawczynski  ?

**Comment by charleskawczynski** [comment]
> Does #861 interfere with this @charleskawczynski ?

In terms of conflicts, there's a small conflict in `AtmosModel`, but that's the only conflict. Not sure if there are any interacting problems though (if #861 uses `PlanetParameters`). I still need to try this on the slurm tests.

**Pull request merged**
