### PR TITLE
Adding Ocean tests to Azure

### PR DESCRIPTION
**Pull request by blallen**
# Description

This PR removes the old Ocean tests (which are now deprecated) and starts introducing tests to run on Azure CI in addition to the tests on Slurm CI. This will include some short physics tests as well as unit tests for different Ocean configurations. For now, all new test files will be in the `test/Ocean/HydrostaticBoussinesq` directory.

- `test_divergence_free.jl` - tests the basic machinery and ensures our code remains incompressible. Uses the `HomogeneousBox` problem set-up which includes the `CoastlineNoSlip`, `OceanFloorFreeSlip`, and `OceanSurfaceStressNoForcing` boundary conditions. Runs for 60 timesteps of 60 seconds each. Tests do fail if the timestep is larger and breaks incompressibility.
- `test_ocean_gyre.jl` -  tests the `OceanGyre` problem set-up which will add `OceanFloorNoSlip` and `OceanSurfaceStressForcing` boundary conditions to our tests. Runs for 60 timesteps of 6 seconds explicitly and 6 timesteps of 60 seconds with vertical IMEX. Does not test any physics, just if the code will run.

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by blallen** [comment]
bors try

**Comment by blallen** [comment]
@simonbyrne, is there any reason for an Azure test to take >40 minutes on a Linux machine when it finished in 262 seconds on a macOS machine and 336 seconds on a Windows machine?

**Comment by kpamnany** [comment]
This is an unresolved question. See #670.

**Comment by simonbyrne** [comment]
I'm not sure what to do about the linux slow down.

**Comment by kpamnany** [comment]
On the bright side, it's just Azure. On SlurmCI, the performance is fine.

**Comment by kpamnany** [comment]
Sorry @blallen, but I think we need to rethink this if CI is going to take 3 hours for every commit. Let's figure out the best way to address this before we add this much time?

**Comment by blallen** [comment]
@kpamnany, I reduced the number of elements and things run much faster now :)

**Comment by kpamnany** [comment]
I can't see the Azure log because of conflicts. :(  Squash and rebase please?

**Comment by blallen** [comment]
Proper squash and rebase accomplished now

**Pull request merged**
