### PR TITLE
Vtk should be VTK

### PR DESCRIPTION
**Pull request by jkozdon**
Total yak shaving, but VTK is an acronym for Visualization Toolkit [1]
and should be all caps

[1] https://vtk.org/

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Should we also change `writevtk` to `writeVTK`? No, right?

**Comment by simonbyrne** [comment]
happy to merge for now. I'll leave it up to @jkozdon if he wants to change `writevtk`

**Comment by jkozdon** [comment]
> Should we also change `writevtk` to `writeVTK`? No, right?

I could go either way. The filename has a lowercase `.vtk` so maybe not?

**Pull request merged**
