### PR TITLE
Add travis and appveyor to bors

### PR DESCRIPTION
**Pull request by jkozdon**

### CODE REVIEW

**Comment by jkozdon** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
Not sure if 1f77a92 is a good idea or not... don't know enough about bors to understand the implication if it works.

**Comment by jkozdon** [comment]
Do we still want this? I can try rebase is an try again if so.

**Pull request closed without merging**
