### PR TITLE
Dry phase

### PR DESCRIPTION
**Pull request by charleskawczynski**
Added `PhaseDry` `ThermodynamicState` and method support

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by simonbyrne** [comment]
Do you want to merge this in first? Or wait for #333.

**Comment by charleskawczynski** [comment]
They're orthogonal :), so we shouldn't have any conflicts. It might be nice to merge this, then we can update #333 to use the dry thermo state for the `DryModel()`

**Pull request merged**
