### PR TITLE
Update BC for OceanModel to account for inflow boundary flux implementation

### PR DESCRIPTION
**Pull request by blallen**
# Description

See title. This ports the changes discussed [here](https://github.com/CliMA/ClimateMachine.jl/pull/851#issuecomment-652072959) to the SplitExplicit01 model. Also adds `simple_box_2dt.jl` to the tests.

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [x] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by blallen** [comment]
bors try

**Comment by blallen** [comment]
@jm-c can you check the solutions with the updated boundary conditions and make sure everything is okay? The state check values are pretty close, but I know those only run for a short time period.

**Comment by jm-c** [comment]
These changes fix/remove the factor of 2 in surface second-order fluxes (that got fixed in other Ocean BC code back on MAy 30,
PR #851). However, it does not address all the other second-order flux BC that remains different in SplitExplicit01 code
and remaining ocean code. For instance: 
 line 147 in src/Ocean/HydrostaticBoussinesq/bc_velocity.jl
 line 132 in src/Ocean/SplitExplicit01/OceanBoundaryConditions.jl  
I don't  recommend to merge-in this (incomplete) set of changes (as I already mentioned this morning at our meeting).

**Comment by blallen** [comment]
Ah okay, I see what you mean now. I will update in those places as well.

**Comment by blallen** [comment]
@jm-c can you check this before I update the state check values again?

**Comment by jm-c** [comment]
@blallen  I have 3 comments:
1) Can we keep the state-check output "Label" names ? not clamming the original one are the best but just so that
a) easier to compare what this modification implies in term of result changes ; b) would be easy to check on my side that I get
zero diff (I have a version of updated BC which I use for testing); c) unless we are fully sure: everything is correct, it's not a bad
practice to separate changes that do change results from others that just involve renaming things.
2) not sure about line 151 in new version of OceanBoundaryConditions.jl
3) not strictly related to this PR, but rather to PR #1583 : since the order of arguments in fct ocean_boundary_state has changed
(used to be: Model, type-of-BC, type-of-flux ; now: type-of-flux, type-of-BC, Model), it would be nice to have the description updated to reflect what the function is doing.

**Comment by jkozdon** [comment]
@blallen can you close this? Seems pretty stale.

**Comment by jkozdon** [comment]
> @blallen can you close this? Seems pretty stale.

Thanks @blallen. Was cleaning out my github dashboard, and saw these. Since I am no longer part of the clima organization I couldn't unrequest my review.

Hope that you are doing well.

**Pull request closed without merging**
