### PR TITLE
Add `Courant` module

### PR DESCRIPTION
**Pull request by charleskawczynski**
Adds Courant module, broken off from #610

There aren't any unit tests for this module, but it would be nice to add some eventually.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
@simonbyrne ready to merge after review

**Comment by tapios** [comment]
A couple issues:

1. We only need to distinguish between horizontal and vertical Courant numbers (additional distinctions in the horizontal seem unnecessary to me).
2. This needs clearer variable names (e.g., `Courant_sound_horiz` instead of `Courssx`).
3. It is also unclear to me where 'Dx' etc come from. Is this from `min_node_distance`, or from a local minimum nodal distance on the element where velocities are evaluated? I think the simple evaluation based on a global minimum nodal distance (distinguishing horizontal and vertical, and advective velocities and sound speeds) would suffice.

**Comment by smarras79** [comment]
> A couple issues:
> 
> 1. We only need to distinguish between horizontal and vertical Courant numbers (additional distinctions in the horizontal seem unnecessary to me).
> 2. This needs clearer variable names (e.g., `Courant_sound_horiz` instead of `Courssx`).
> 3. It is also unclear to me where 'Dx' etc come from. Is this from `min_node_distance`, or from a local minimum nodal distance on the element where velocities are evaluated? I think the simple evaluation based on a global minimum nodal distance (distinguishing horizontal and vertical, and advective velocities and sound speeds) would suffice.
> 
> Need @fxgiraldo review.

Perfect, I will change it.

**Comment by fxgiraldo** [comment]
Yes, I agree with only requiring horizontal vs vertical Courant numbers. Regarding whether to use the minimum global spacing or per element could matter for highly unstructured/stretched grids.  Now that @smarras79 has pointed me to a working branch with the Courant numbers, I can add my test cases and compare the time-steps and Courant number computations with NUMA.

**Comment by tapios** [comment]
To simply matters, I suggest you focus on advective and diffusive Courant numbers only. The speed of sound varies only by ~20% in the atmosphere, so the acoustic Courant number is more or less fixed by a reference speed of sound and the minimum nodal distance. This can be calculated offline once. The advective and diffusive Courant numbers are the ones that vary and that we would want to monitor.

**Comment by kpamnany** [comment]
I don't think this should go in `Diagnostics`, rather in `ODESolvers`.

**Comment by smarras79** [comment]
> I don't think this should go in `Diagnostics`, rather in `ODESolvers`.

@kpamnany  don't worry Courant.jl because it is being replaced in full by #618

**Comment by simonbyrne** [comment]
sdiff in #612 seems to be just extracting one of the diagonal components of the tensor to make a scalar (or am I misunderstanding it?) We should probably do something more principled, but I would like to know what that is.

#612 also seems to make the implicit assumption that the dg grid is Cartesian aligned

**Pull request closed without merging**
