### PR TITLE
Grid stretching function in Grids.jl + MWE

### PR DESCRIPTION
**Pull request by smarras79**
Added `function grid_stretching_cube` to `Grids.jls`

- This function stretches a grid in the vertical direction for the flow in a box.
- It is ready to add stretching towards an attraction point in the X and Y direction. A proper function should be selected for that.

The stretching must be called right before building the `brickrange` in the driver.
See `test/DGmethods/compressible_Navier_Stokes/MWE_grid_stretching.jl`

### CODE REVIEW

**Comment by jkozdon** [comment]
I'd propose a couple things with this:

- I don't think that 'Grids.jl` is the right place for this, `Topologies.jl` would be better
- This isn't really a grid stretching in the way we define "grid" (for better or worse) in the code, but an element stretching or something like this; in clima "grid" tends to mean actual degrees of freedom whereas topology is the elements without degrees of freedom
- would it be better to have a function that handles each dimension separately. For example, right now we do things like
```julia
brickrange = (range(DFloat(0); length=Ne[1]+1, stop=1),
              range(DFloat(0); length=Ne[2]+1, stop=1),
              range(DFloat(0); length=Ne[2]+1, stop=1))
```
we could add an `exprange` function (or something like this) so the user could do
```julia

brickrange = (range(DFloat(0); length=Ne[1]+1, stop=1),
              range(DFloat(0); length=Ne[2]+1, stop=1),
              exprange(DFloat(0); length=Ne[2]+1, stop=1))
```
which would use an exponential stretching in the vertical dimension.
- Another question is should this stretching be done before or after the degrees of freedom are layed down (@lcw might have some thoughts on this)

**Comment by smarras79** [comment]
> I'd propose a couple things with this:
> 
> * I don't think that 'Grids.jl`is the right place for this,`Topologies.jl` would be better

No problem, I will move it to topology.

> * This isn't really a grid stretching in the way we define "grid" (for better or worse) in the code, but an element stretching or something like this; in clima "grid" tends to mean actual degrees of freedom whereas topology is the elements without degrees of freedom
> * would it be better to have a function that handles each dimension separately. For example, right now we do things like
> 
> ```julia
> brickrange = (range(DFloat(0); length=Ne[1]+1, stop=1),
>               range(DFloat(0); length=Ne[2]+1, stop=1),
>               range(DFloat(0); length=Ne[2]+1, stop=1))
> ```
> 
> we could add an `exprange` function (or something like this) so the user could do
> 
> ```julia
> brickrange = (range(DFloat(0); length=Ne[1]+1, stop=1),
>               range(DFloat(0); length=Ne[2]+1, stop=1),
>               exprange(DFloat(0); length=Ne[2]+1, stop=1))
> ```
> 
> which would use an exponential stretching in the vertical dimension.
> 

I will work something in this way.

> * Another question is should this stretching be done before or after the degrees of freedom are layed down (@lcw might have some thoughts on this)

I would do it at the moment when the topology is built. I would imagine that this is done before the dof are layed down.

**Comment by smarras79** [comment]
bors try

**Comment by smarras79** [comment]
bors try

**Comment by smarras79** [comment]
bors try

**Comment by jkozdon** [comment]
Since this is not tested in anyway should it really be merged?

**Comment by smarras79** [comment]
> Since this is not tested in anyway should it really be merged?

In what sense it is not tested in any way?

**Comment by jkozdon** [comment]
> In what sense it is not tested in any way?

Three files are changed: 
- `src/Mesh/Grids.jl`
- `src/Mesh/Topologies.jl`
- `test/DGmethods/compressible_Navier_Stokes/MWE_grid_stretching.jl`

None of these add tests to the code, so during CI none of this code is run.

**Comment by smarras79** [comment]
Give me a clear procedure to follow and I'll do that.

**Comment by jkozdon** [comment]
See PR https://github.com/climate-machine/CLIMA/pull/323

**Comment by jkozdon** [comment]
FYI right now this code does not run on either the CPU or GPU if you are on a fresh version of master

CPU:
```
❯ julia --project test/DGmethods/compressible_Navier_Stokes/MWE_grid_stretching.jl
ERROR: LoadError: ArgumentError: Package TimerOutputs not found in current path:
- Run `import Pkg; Pkg.add("TimerOutputs")` to install the TimerOutputs package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:876
 [2] include at ./boot.jl:328 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1094
 [4] include(::Module, ::String) at ./Base.jl:31
 [5] exec_options(::Base.JLOptions) at ./client.jl:295
 [6] _start() at ./client.jl:464
in expression starting at /home/jekozdon/codes/CLIMA/test/DGmethods/compressible_Navier_Stokes/MWE_grid_stretching.jl:20
```

GPU:
```
❯ julia --project=env/gpu test/DGmethods/compressible_Navier_Stokes/MWE_grid_stretching.jl
ERROR: LoadError: ArgumentError: Package TimerOutputs not found in current path:
- Run `import Pkg; Pkg.add("TimerOutputs")` to install the TimerOutputs package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:876
 [2] include at ./boot.jl:328 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1094
 [4] include(::Module, ::String) at ./Base.jl:31
 [5] exec_options(::Base.JLOptions) at ./client.jl:295
 [6] _start() at ./client.jl:464
in expression starting at /home/jekozdon/codes/CLIMA/test/DGmethods/compressible_Navier_Stokes/MWE_grid_stretching.jl:20
```

**Comment by smarras79** [comment]
You need to add timer TimerOutputs. @lcw added it to time the code. 
All my this PR does is adding a grid stretching to Topology.

**Comment by smarras79** [comment]
How did it pass all the bors tests then? I may not be understanding how bors work.
The code works on the GPU cluster at caltech and the tests of the PR indicate that the code works correctly.

**Comment by jkozdon** [comment]
> You need to add timer TimerOutputs.

The user should not need to add these. They should be part of the `Project.toml`

> @lcw added it to time the code.

@lcw added this to a branch that never was merged into master, thus it never became part of CLIMA. You pulled the file out of the branch without the support changes

> How did it pass all the bors tests then? I may not be understanding how bors work. 

bors only runs the tests listed in the `runtest.jl` files and the `.slurmci` directory. It does not/cannot determine what files are tests and not. Nor how to run them.

> The code works on the GPU cluster at caltech 

I'm guessing you have `TimerOutputs` in your local `julia` environment but they are not in the CLIMA project environment.

> and the tests of the PR indicate that the code works correctly.

Since the CI does not run your code, the CI that ran did not include your code only what was already on master (which passed CI since it's already in master).

**Comment by jkozdon** [comment]
If you launch julia without `--project` and type `]status` you'll see what packages you are using that are not part of CLIMA but your local environment.

**Comment by smarras79** [comment]
> > You need to add timer TimerOutputs.
> 
> The user should not need to add these. They should be part of the `Project.toml`

I thought we were not supposed to modify the Project.toml and only the reviewer of the PR could do that. 
I will add that and update the PR.

> 
> > @lcw added it to time the code.
> 
> @lcw added this to a branch that never was merged into master, thus it never became part of CLIMA. You pulled the file out of the branch without the support changes
> 
> > How did it pass all the bors tests then? I may not be understanding how bors work.
> 
> bors only runs the tests listed in the `runtest.jl` files and the `.slurmci` directory. It does not/cannot determine what files are tests and not. Nor how to run them.
> 
> > The code works on the GPU cluster at caltech
> 
> I'm guessing you have `TimerOutputs` in your local `julia` environment but they are not in the CLIMA project environment.
> 
> > and the tests of the PR indicate that the code works correctly.
> 
> Since the CI does not run your code, the CI that ran did not include your code only what was already on master (which passed CI since it's already in master).

**Comment by jkozdon** [comment]
> I thought we were not supposed to modify the Project.toml

Random changes shouldn't be made that is true, but if its need they should be.

> and only the reviewer of the PR could do that.

No one reviewed your PR.

If you want someone to review your PRs you need to ask them to. I did make some comments on the PR earlier, but this wasn't so much a review as structural suggestions.

**Comment by smarras79** [comment]
> > I thought we were not supposed to modify the Project.toml
> 
> Random changes shouldn't be made that is true, but if its need they should be.
> 
> > and only the reviewer of the PR could do that.
> 
> No one reviewed your PR.
> 
> If you want someone to review your PRs you need to ask them to. I did make some comments on the PR earlier, but this wasn't so much a review as structural suggestions.

Yes, those comments have been addressed to improve the code.

**Comment by jkozdon** [comment]
Look at PR #327 for how to add tests (I found a missing isentropic vortex test)

**Pull request merged**
