### PR TITLE
Upgrade MPI.jl version

### PR DESCRIPTION
**Pull request by jkozdon**
This only update MPI.jl whereas #372 update CUDA dependencies as well.

### CODE REVIEW

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
@simonbyrne or @lcw: You ever seen this one?

```
error: Invalid bitcode signature
```

https://gist.github.com/climabot/06189d80ea9be303c5cbf50ed401f271#file-out_6105166

also happened on the previous bors try

https://gist.github.com/climabot/a5bc48f22284b2f18c576a2846c8485d#file-out_6105089

Both are gpu tests.

**Comment by simonbyrne** [comment]
No, that is really odd.

Could maybe try downgrading to openmpi/3.1.4?

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
That seemed to work, so we can go with this once the cluster is back up.

I'll try to figure out the issue with 4.0.1 once the cluster is back up.

**Comment by lcw** [comment]
> @simonbyrne or @lcw: You ever seen this one?
> 
> ```
> error: Invalid bitcode signature
> ```

Unfortunately, nope.

**Pull request merged**
