### PR TITLE
add gravitational_potential function

### LINKED ISSUE #423: Fix gravity in `mms_bc_atmos`
In #420 we needed to added a `NoOrientation` to fully remove gravity. This needs to be done in [`mms_bc_atmos.jl`](https://github.com/climate-machine/CLIMA/blob/2656cde7a8a240d6e4493619f316f084d6a74ab5/test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl) as well. This is because the [`internal_energy`](https://github.com/climate-machine/CLIMA/blob/2656cde7a8a240d6e4493619f316f084d6a74ab5/src/Atmos/Model/moisture.jl#L20-L29) function uses `aux.orientation.Φ`

### PR DESCRIPTION
**Pull request by simonbyrne**
Provide a standard interface for accessing gravitational potential. Fixes #423.

### CODE REVIEW

**Comment by jkozdon** [comment]
`mms_bc_atmos` then needs to use a `Orientation` that sets the gravitational potential to zero.

Something like
```julia
struct NoOrientation <: Orientation
end
gravitational_potential(::NoOrientation, aux::Vars) = -zero(eltype(aux))
```

**Comment by jkozdon** [comment]
Should we fix `mms_bc_atmos` before this is merged?

**Comment by charleskawczynski** [comment]
Ah, you're right. bors r-

**Comment by charleskawczynski** [comment]
Simon added the struct, but it's not implemented in mms_bc_atmos yet. I'll add it now.

**Comment by charleskawczynski** [comment]
Wait, how did this pass then?

**Comment by charleskawczynski** [comment]
Oh, right. The domain in `mms_bc_atmos` is between 0 and 1, so the gravitational potential is extremely small.

This does need to be fixed, but when I run 
```
git fetch origin
git checkout -b sb/gravpot origin/sb/gravpot
git merge master
```
I'm getting `fatal: 'origin/sb/gravpot' is not a commit and a branch 'sb/gravpot' cannot be created from it`. I can just update this after, if that's okay @jkozdon. Or, you can change it if you're able. I'm fine either way.

**Comment by jkozdon** [comment]
@charleskawczynski I've pushed out the update. Any chance you have time to kick off a job on the cluster to make sure the integration testing is still OK?

Also, I think for your git command you wanted:
```
git fetch origin
git checkout origin/sb/gravpot -b sb/gravpot
git merge master
```

**Comment by charleskawczynski** [comment]
Thanks

> Any chance you have time to kick off a job on the cluster to make sure the integration testing is still OK?

Yes, I think so. I'll let you know by the end of the day if I'm unable to.

**Comment by charleskawczynski** [comment]
@jkozdon Ready to merge

**Pull request merged**
