### PR TITLE
Moved PlanetParameters to Common

### LINKED ISSUE #347: Move `PlanetParameters` to `Common` folder

### PR DESCRIPTION
**Pull request by charleskawczynski**
To close #347

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
Sorry, accidentally deleted this branch, thought it had merged already

**Comment by simonbyrne** [comment]
can you restore? https://help.github.com/en/articles/deleting-and-restoring-branches-in-a-pull-request

**Comment by simonbyrne** [comment]
oh wait, it has been merged: https://github.com/climate-machine/CLIMA/commit/5f3420dfd377e807f44485fd22ec5b2d3295b6bb

**Comment by charleskawczynski** [comment]
Yeah, sorry, I was confused when I saw the conflict

**Pull request merged**
