### PR TITLE
Remove PlanetParameters from most experiments

### PR DESCRIPTION
**Pull request by charleskawczynski**
# Description

Remove `PlanetParameters` from all experiments except `ocean_gyre.jl`.

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/format.jl`

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by charleskawczynski** [comment]
The GPU run of `pseudo1D_advection_diffusion.jl` is timing out. @simonbyrne @jkozdon any idea what to do here? I didn't even touch `pseudo1D_advection_diffusion.jl`

**Comment by blallen** [comment]
Why except `ocean_gyre.jl`? It should be the same change as in `homogeneous_box.jl`.

**Comment by charleskawczynski** [comment]
It should, but #874 was b-o-r-s-r+'d just before I tried to merge #868, and I didn't want to for CI to complete to rebase. It didn't turn out to matter anyway since the CI is timing out.

**Comment by jkozdon** [comment]
> The GPU run of `pseudo1D_advection_diffusion.jl` is timing out. @simonbyrne @jkozdon any idea what to do here? I didn't even touch `pseudo1D_advection_diffusion.jl`

No clue. Sorry.

**Pull request merged**
