### PR TITLE
[TurbConv] Updated docs

### PR DESCRIPTION
**Pull request by charleskawczynski**
- Added definitions for coefficients in BCs
 - Fixed coefficient in cross-gradient flux source term
 - Fixed buoyancy flux name (used to be theta, now b)
 - Removed unused source term

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Do not merge yet, I'd like to make sure it builds successfully

**Comment by jkozdon** [comment]
> Do not merge yet, I'd like to make sure it builds successfully

On a tangential note: would it be useful to add to the bors.toml `block_labels = [ "do-not-merge-yet" ]` to prevent bors from merging PRs which have this label. See [here](https://bors.tech/documentation/#configuration-borstoml).

**Comment by charleskawczynski** [comment]
> > Do not merge yet, I'd like to make sure it builds successfully
> 
> On a tangential note: would it be useful to add to the bors.toml `block_labels = [ "do-not-merge-yet" ]` to prevent bors from merging PRs which have this label. See [here](https://bors.tech/documentation/#configuration-borstoml).

I like that idea!

**Pull request merged**
