### PR TITLE
change to submodules instead of subpackages

### LINKED ISSUE #106: Move to single package with submodules
We discussed this on Slack a bit, but should we move to a single global Project file, and make the subpackages be just submodules?

The main advantage is that we won't have to spend as much time editing and updating Manifest and Project files manually. I suspect this will get more difficult as we continue to add more functionality.

One downside is that you won't be able `] test` a single subpackage any longer: we could keep the current directory structure, so you could still manually `include("submodule/test/runtests.jl")` if you wanted.

For the GPU support, I was thinking we could have an `env/gpu` subdirectory, along with a simple script which copies the top-level Project.toml, adds the GPU dependencies, and resolves as necessary.

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #106.

The main changes turned out to be:
- adding/removing dependencies is now done in the main Project.toml file
- submodules need to be manually `include`ed from `src/CLIMA.jl`
- instead of `using SubModule` you now do:
  - for package code: `using ..SubModule` (potentially adding more `.`s at the end if you are in nested submodules)
  - for tests: `using CLIMA.SubModule`

Overall it seems a bit easier to maintain. I'll see if I can figure out a neat way to handle the GPU environment.

### CODE REVIEW

**Comment by simonbyrne** [comment]
I think we will probably want to flatten the directory structure to match the module structure (#8).

**Comment by simonbyrne** [comment]
@charleskawczynski asked me how you would run a single test file using this structure. The idea is that you should be able to just do
```
julia --project runtests.jl
```
from any subdirectory and it should "just work" (or alternatively, start julia with `julia --project` and `include` from there).

To use GPUs, you would do
```
julia --project=../../env/gpu runtests.jl
```
(replacing `../../` with the necessary number of levels)

**Comment by simonbyrne** [comment]
actually it turns out you can just do
```
julia --project=@./env/gpu runtests.jl
```
from any subdirectory!

**Comment by simonbyrne** [comment]
(also note that this supersedes #100)

**Comment by lcw** [comment]
On the CPU everything seems to work!

I am having a couple of problems getting it to run on the GPU.  First,
```
julia --project=@./env/gpu 
```
doesn't find the environment for me.  Second, I am unable to instantiate the GPU environment
with ` julia --project=../../../env/gpu/ -e 'using Pkg; Pkg.instantiate()'`
```
~/julia/code/CLIMA/src/ClimaAtmos/Dycore sb/env* lucasw@koelsch
❯ mv ~/.julia/ ~/.julia_old

~/julia/code/CLIMA/src/ClimaAtmos/Dycore sb/env* lucasw@koelsch
❯ julia --project=../../../env/gpu/ -e 'using Pkg; Pkg.instantiate()'
   Cloning default registries into `~/.julia`
   Cloning registry from "https://github.com/JuliaRegistries/General.git"
     Added registry `General` to `~/.julia/registries/General`
   Cloning git-repo `https://github.com/climate-machine/Canary.jl`
   Cloning git-repo `.`
ERROR: Git repository not found at '.'
Stacktrace:
 [1] pkgerror(::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:120
 [2] #clone#3(::Nothing, ::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:isbare, :credentials),Tuple{Bool,LibGit2.CachedCredentials}}}, ::Function, ::String, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/GitTools.jl:109
 [3] #clone at ./none:0 [inlined]
 [4] #ensure_clone#2 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/GitTools.jl:87 [inlined]
 [5] (::getfield(Pkg.GitTools, Symbol("#kw##ensure_clone")))(::NamedTuple{(:isbare, :credentials),Tuple{Bool,LibGit2.CachedCredentials}}, ::typeof(Pkg.GitTools.ensure_clone), ::String, ::String) at ./none:0
 [6] #handle_repos_add!#61(::Bool, ::Nothing, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:735
 [7] #handle_repos_add! at ./none:0 [inlined]
 [8] #instantiate#65(::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:466
 [9] instantiate at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:437 [inlined]
 [10] #instantiate#64 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:435 [inlined]
 [11] instantiate() at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:435
 [12] top-level scope at none:0
```

Is there something else I need to do?

**Comment by simonbyrne** [comment]
> I am having a couple of problems getting it to run on the GPU. First,
> 
> ```
> julia --project=@./env/gpu 
> ```
> doesn't find the environment for me.

Unfortunately I realised that after I wrote it.



> Second, I am unable to instantiate the GPU environment
> with ` julia --project=../../../env/gpu/ -e 'using Pkg; Pkg.instantiate()'`

I've just pushed a small change: can you try it again?

**Comment by lcw** [comment]
It now finds the environment!  But I think the version of CUDAnative got upgraded in the manifest so the code doesn't run.  We need to update to the latest CUDAnative sooner than later.

**Comment by simonbyrne** [comment]
Ah ok. Can you push the necessary changes to this branch? Otherwise I can
look at it Monday.

**Comment by lcw** [comment]
I pushed changes to upgrade to using the CuArrays package but now we have a problem with their `fill!` command failing.  I got the following error message

```
~/julia/code/CLIMA/src/ClimaAtmos/Dycore sb/env* lucasw@koelsch
❯ julia12 --project=../../../env/gpu/ drivers/isentropic_vortex.jl
┌ Warning: The two argument form of `func_for_method_checked` is deprecated. Pass sparams in addition.
│   caller = irgen(::CUDAnative.CompilerContext) at irgen.jl:108
└ @ CUDAnative ~/.julia/packages/CUDAnative/Mdd3w/src/compiler/irgen.jl:108
[ Info: Building the CUDAnative run-time library for your sm_70 device, this might take a while...
ERROR: Error while loading expression starting at /home/lucasw/julia/code/CLIMA/src/ClimaAtmos/Dycore/drivers/isentropic_vortex.jl:178
caused by [exception 1]
InexactError: trunc(Int64, NaN)
Stacktrace:
 [1] trunc at ./float.jl:696 [inlined]
 [2] ceil at ./float.jl:359 [inlined]
 [3] thread_blocks_heuristic at /home/lucasw/.julia/packages/GPUArrays/t8tJB/src/heuristics.jl:4 [inlined]
 [4] gpu_call(::Function, ::CuArray{Float64,3}, ::Tuple{CuArray{Float64,3},Float64}, ::Int64) at /home/lucasw/.julia/packages/GPUArrays/t8tJB/src/abstract_gpu_interface.jl:131
 [5] gpu_call at /home/lucasw/.julia/packages/GPUArrays/t8tJB/src/abstract_gpu_interface.jl:128 [inlined]
 [6] fill! at /home/lucasw/.julia/packages/GPUArrays/t8tJB/src/construction.jl:10 [inlined]
 [7] AtmosStateArray{Tuple{25,15},Float64,CuArray,N,DATN,Nm1,DAI1} where DAI1 where Nm1 where DATN<:AbstractArray{Float64,N} where N(::MPI.Comm, ::Int64, ::UnitRange{Int64}, ::UnitRange{Int64}, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{UnitRange{Int64},1}, ::Array{UnitRange{Int64},1}, ::Array{Float64,2}) at /home/lucasw/julia/code/CLIMA/src/ClimaAtmos/Dycore/src/AtmosStateArrays.jl:59
 [8] #call#1 at /home/lucasw/julia/code/CLIMA/src/ClimaAtmos/Dycore/src/AtmosStateArrays.jl:93 [inlined]
 [9] Type at ./none:0 [inlined]
 [10] (::getfield(CLIMA.CLIMAAtmosDycore.VanillaAtmosDiscretizations, Symbol("##call#2#4")))(::Bool, ::Int64, ::Type{VanillaAtmosDiscretization{0,0,polynomialorder,numberofDOFs,DeviceArray,nmoist,ntrace,DASAT3,GT} where GT where DASAT3 where ntrace where nmoist where DeviceArray where numberofDOFs where polynomialorder}, ::DiscontinuousSpectralElementGrid{Float64,2,4,25,CuArray,CuArray{Float64,2},CuArray{Float64,3},CuArray{Float64,4},CuArray{Int64,1},CuArray{Int64,2},CuArray{Int64,3},BrickTopology{2,Float64}}) at /home/lucasw/julia/code/CLIMA/src/ClimaAtmos/Dycore/src/VanillaAtmosDiscretizations.jl:63
 [11] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:gravity,),Tuple{Bool}}, ::Type{VanillaAtmosDiscretization{0,0,polynomialorder,numberofDOFs,DeviceArray,nmoist,ntrace,DASAT3,GT} where GT where DASAT3 where ntrace where nmoist where DeviceArray where numberofDOFs where polynomialorder}, ::DiscontinuousSpectralElementGrid{Float64,2,4,25,CuArray,CuArray{Float64,2},CuArray{Float64,3},CuArray{Float64,4},CuArray{Int64,1},CuArray{Int64,2},CuArray{Int64,3},BrickTopology{2,Float64}}) at ./none:0
 [12] (::getfield(CLIMA.CLIMAAtmosDycore.VanillaAtmosDiscretizations, Symbol("##VanillaAtmosDiscretization#1#3")))(::Int64, ::Int64, ::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:gravity,),Tuple{Bool}}}, ::Type{VanillaAtmosDiscretization}, ::DiscontinuousSpectralElementGrid{Float64,2,4,25,CuArray,CuArray{Float64,2},CuArray{Float64,3},CuArray{Float64,4},CuArray{Int64,1},CuArray{Int64,2},CuArray{Int64,3},BrickTopology{2,Float64}}) at /home/lucasw/julia/code/CLIMA/src/ClimaAtmos/Dycore/src/VanillaAtmosDiscretizations.jl:47
 [13] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:gravity,),Tuple{Bool}}, ::Type{VanillaAtmosDiscretization}, ::DiscontinuousSpectralElementGrid{Float64,2,4,25,CuArray,CuArray{Float64,2},CuArray{Float64,3},CuArray{Float64,4},CuArray{Int64,1},CuArray{Int64,2},CuArray{Int64,3},BrickTopology{2,Float64}}) at ./none:0
 [14] #main#3(::Float64, ::Bool, ::Int64, ::typeof(main), ::MPI.Comm, ::Type, ::Type, ::Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}, ::Int64, ::Float64, ::Type) at /home/lucasw/julia/code/CLIMA/src/ClimaAtmos/Dycore/drivers/isentropic_vortex.jl:106
 [15] (::getfield(Main, Symbol("#kw##main")))(::NamedTuple{(:dt,),Tuple{Float64}}, ::typeof(main), ::MPI.Comm, ::Type, ::Type, ::Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}, ::Int64, ::Float64, ::Type) at ./none:0
 [16] top-level scope at /home/lucasw/julia/code/CLIMA/src/ClimaAtmos/Dycore/drivers/isentropic_vortex.jl:195
 [17] include at ./boot.jl:325 [inlined]
 [18] include_relative(::Module, ::String) at ./loading.jl:1042
 [19] include(::Module, ::String) at ./Base.jl:29
 [20] exec_options(::Base.JLOptions) at ./client.jl:295
 [21] _start() at ./client.jl:464
```

I'll have to look at fixing this on Monday as well.

**Comment by simonbyrne** [comment]
Great, thanks for your help.

**Comment by simonbyrne** [comment]
@lcw Do you think you'll get this working today? If not, I might merge this as it's holding up some other work and we can fix it on a separate branch.

**Comment by lcw** [comment]
I found the source of the issue I was seeing Friday.  You can't fill a CuArray of length 0.  For example

```
~/julia/code/CLIMA sb/env* lucasw@koelsch
❯ julia --project=env/gpu/
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(gpu) pkg> using CuArrays
ERROR: could not determine command

julia> using CuArrays

julia> a = Array{Float64}(undef, 0)
0-element Array{Float64,1}

julia> fill!(a, 0)
0-element Array{Float64,1}

julia> fill!(CuArray(a), 0)
ERROR: InexactError: trunc(Int64, NaN)
Stacktrace:
 [1] trunc at ./float.jl:696 [inlined]
 [2] ceil at ./float.jl:359 [inlined]
 [3] thread_blocks_heuristic at /home/lucasw/.julia/packages/GPUArrays/t8tJB/src/heuristics.jl:4 [inlined]
 [4] gpu_call(::Function, ::CuArray{Float64,1}, ::Tuple{CuArray{Float64,1},Float64}, ::Int64) at /home/lucasw/.julia/packages/GPUArrays/t8tJB/src/abstract_gpu_interface.jl:131
 [5] gpu_call at /home/lucasw/.julia/packages/GPUArrays/t8tJB/src/abstract_gpu_interface.jl:128 [inlined]
 [6] fill!(::CuArray{Float64,1}, ::Int64) at /home/lucasw/.julia/packages/GPUArrays/t8tJB/src/construction.jl:10
 [7] top-level scope at none:0
```

so for now I will put guards in the code to make sure the array is of nonzero length.

**Comment by simonbyrne** [comment]
Okay thanks. Maybe open an upstream issue so that we can keep track of it as well.

**Comment by lcw** [comment]
The issue seems to be fixed on `CuArrays#master`, so when we upgrade we can remove the checks.  I am ready fo this to merge.

**Comment by lcw** [comment]
Oops, spoke too soon.  The issue is not fixed upstream.  I will work on filling an issue/fix for CuArrays.

**Comment by lcw** [comment]
The upstream pr for the `fill!` issue is here https://github.com/JuliaGPU/GPUArrays.jl/pull/185.

**Pull request merged**
