### PR TITLE
Add dims argument to norm

### PR DESCRIPTION
**Pull request by simonbyrne**
This is a revamp of #406 (I didn't want to force-push to that branch). Instead of defining new functions, this just adds a keyword `dims` argument to `norm`

### CODE REVIEW

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by charleskawczynski** [comment]
> ## try
> # Merge conflict

What's this mean? Is this referring to the try previous to r plus?

**Comment by simonbyrne** [comment]
I'm not sure...

**Pull request merged**
