### PR TITLE
Run integration tests in slurm testing

### LINKED ISSUE #337: Integration Testing
Right now the integration tests are not being run automatically. Should we turn on integration testing via `JULIA_CLIMA_INTEGRATION_TESTING` for the slurm runs?

cc: @mwarusz

### PR DESCRIPTION
**Pull request by jkozdon**
To close #337

### CODE REVIEW

**Comment by jkozdon** [comment]
bors try

**Comment by lcw** [comment]
If the tests pass and don't take too long, looks good to me!

**Comment by jkozdon** [comment]
@simonbyrne: Do you know if this Is this still running on the caltech cluster? If so, probably guessing that one of the tests is taking a long time with full integration testing turned on...

**Comment by jkozdon** [comment]
bors try-

**Comment by jkozdon** [comment]
bors try

**Comment by simonbyrne** [comment]
Yes, it does look like some are timing out, but there are also some failures.

You can try to extend the timeout?

**Comment by jkozdon** [comment]
> Yes, it does look like some are timing out, but there are also some failures.

For some reason my initial `bors try` failed to launch. Hence my question this morning. After posting the message to you I decided to `bors try` again and it went through.

**Comment by jkozdon** [comment]
This seems like it'll be a bit of mess to get working. Since most of these tests are getting phased out, it seems like it would be a waste of time to fix all the issues.

@lcw wondering if we should instead just make sure that the tests we move over to the new framework run the full suite when running on slurm.

**Comment by lcw** [comment]
Jeremy E Kozdon <notifications@github.com> writes:

> @lcw wondering if we should instead just make sure that the tests we
> move over to the new framework run the full suite when running on
> slurm.

This seems reasonable.

**Pull request closed without merging**
