### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by charleskawczynski**

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
Hm, `] pin CuArrays@1.3.0` [didn't do anything](https://github.com/climate-machine/CLIMA/pull/559/files#diff-c77e680c03b450073612b14ccd694a86R131). It was still updated after `] up`.

**Comment by simonbyrne** [comment]
I updated the packages in #493

**Pull request closed without merging**
