### PR TITLE
Throw an exception if norm(Q) == NaN

### LINKED ISSUE #871: Can CLIMA.invoke! raise an error if norm(Q) = NaN?
# Description

This would add an easy way to test the basic physics and numerics of our models, even if we don't have good test cases yet. It would prevent things like #869 from happening silently.

# Additional context

Add any other reasons why this feature will help with the goals of CLIMA.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

### PR DESCRIPTION
**Pull request by kpamnany**
# Description

Closes #871. 

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [X] Followed all necessary [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/format.jl`

# For review by CLIMA developers

- [X] There are no open pull requests for this already
- [X] CLIMA developers with relevant expertise have been assigned to review this submission
- [X] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [X] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by blallen** [comment]
Looks good to me! Do you want me to test it?

**Comment by kpamnany** [comment]
Since you have code that causes this, that'd be great. :)

**Pull request merged**
