### PR TITLE
dycoms3d without sponge

### PR DESCRIPTION
**Pull request by smarras79**
Added dycoms.jl:

Driver for the dycoms benchmark.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Note that docstrings should appear _before_ the function, and use triple double quotes (`"""`) (I've fixed these).

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
@smarras79 This looks like it is now working: can you check the logs look reasonable?:
https://gist.github.com/climabot/99909820aeabc947e90a61c1face3484

Let me know when you're happy to merge it.

**Comment by jkozdon** [comment]
> This looks like it is now working

Is the test that it runs?

**Comment by simonbyrne** [comment]
Yes, at the moment. Would be good to have a more concrete test

**Comment by smarras79** [comment]
@simonbyrne   yes, the test has run as it should. I am happy with merging. 
Thanks

**Comment by simonbyrne** [comment]
Okay, I've squashed this to one commit.

**Pull request merged**
