### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by charleskawczynski**

### CODE REVIEW

**Comment by kpamnany** [comment]
AFAICT, `DifferentialEquations` can be removed...?

**Comment by charleskawczynski** [comment]
> AFAICT, DifferentialEquations can be removed...?

Hm, looks like it.

**Comment by kpamnany** [comment]
Looks like we might need different manifests for Julia 1.2 and Julia 1.3 due to SpecialFunctions (for one). Maybe drop support for Julia 1.2?

**Comment by charleskawczynski** [comment]
Yeah, I'm not sure what the right course of action here is.

**Comment by charleskawczynski** [comment]
@simonbyrne #642 seems to depend on this, and so does incorporating the data files needed in #653. Should we drop support for 1.2?

**Comment by vchuravy** [comment]
One note: Manifest.toml files are not intended to be used with different Julia versions.
What we most likely should start to do is to add Compat bounds to Project.toml, maybe ship one Manifest.toml for users (that we tell to use Julia 1.3) and for CI use the resolver + compat bounds to get the right versions.

I think some folks are using https://github.com/bcbi/CompatHelper.jl to make it easier to update compat bounds to new dependency releases, which would allow us to quicker update dependencies.

**Comment by kpamnany** [comment]
@vchuravy: upgrading to `CuArrays@1.7.0` and the associated `CUDAdrv` and `CUDAnative` produced:
```ERROR: LoadError: CUDA error: a PTX JIT compilation failed (code 218, ERROR_INVALID_PTX)
ptxas application ptx input, line 61; fatal   : Parsing error near '2': syntax error
ptxas fatal   : Ptx assembly aborted due to errors
Stacktrace:
 [1] CUDAdrv.CuModule(::String, ::Dict{CUDAdrv.CUjit_option_enum,Any}) at /home/kpamnany/.julia/packages/CUDAdrv/mCr0O/src/module.jl:41
 [2] macro expansion at /home/kpamnany/.julia/packages/CUDAnative/5NTJF/src/execution.jl:423 [inlined]
 [3] #cufunction#198(::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(CUDAnative.cufunction), ::typeof(GPUArrays.reduce_kernel), ::Type{Tuple{CuArrays.CuKernelState,typeof(identity),typeof(+),Float64,Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArrays.CuArray},Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}},typeof(*),Tuple{CUDAnative.CuDeviceArray{Float64,3,
CUDAnative.AS.Global},Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArrays.CuArray},Nothing,typeof(abs2),Tuple{CUDAnative.CuDeviceArray{Float64,3,CUDAnative.AS.Global}}}}},Val{256},CUDAnative.CuDeviceArray{Float64,1,CUDAnative.AS.Global}}}) at /home/kpamnany/.julia/packages/CUDAnative/5NTJF/src/execution.jl:360
 [4] cufunction(::Function, ::Type) at /home/kpamnany/.julia/packages/CUDAnative/5NTJF/src/execution.jl:360
 [5] macro expansion at /home/kpamnany/.julia/packages/CUDAnative/5NTJF/src/execution.jl:179 [inlined]
 [6] macro expansion at ./gcutils.jl:91 [inlined]
 [7] macro expansion at /home/kpamnany/.julia/packages/CUDAnative/5NTJF/src/execution.jl:176 [inlined]
 [8] _gpu_call(::CuArrays.CuArrayBackend, ::Function, ::CuArrays.CuArray{Float64,1,Nothing}, ::Tuple{typeof(identity),typeof(+),Float64,Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArrays.CuArray},Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}},typeof(*),Tuple{CuArrays.CuArray{Float64,3,CuArrays.CuArray{Float64,3,Nothing}},Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArrays.CuArray},Nothing
,typeof(abs2),Tuple{CuArrays.CuArray{Float64,3,CuArrays.CuArray{Float64,3,Nothing}}}}}},Val{256},CuArrays.CuArray{Float64,1,Nothing}}, ::Tuple{Tuple{Int64},Tuple{Int64}}) at /home/kpamnany/.julia/packages/CuArrays/1njKF/src/gpuarray_interface.jl:62
 [9] gpu_call(::Function, ::CuArrays.CuArray{Float64,1,Nothing}, ::Tuple{typeof(identity),typeof(+),Float64,Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArrays.CuArray},Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}},typeof(*),Tuple{CuArrays.CuArray{Float64,3,CuArrays.CuArray{Float64,3,Nothing}},Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArrays.CuArray},Nothing,typeof(abs2),Tuple{CuArrays
.CuArray{Float64,3,CuArrays.CuArray{Float64,3,Nothing}}}}}},Val{256},CuArrays.CuArray{Float64,1,Nothing}}, ::Tuple{Tuple{Int64},Tuple{Int64}}) at /home/kpamnany/.julia/packages/GPUArrays/1wgPO/src/abstract_gpu_interface.jl:151
 [10] acc_mapreduce(::Function, ::Function, ::Float64, ::Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArrays.CuArray},Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}},typeof(*),Tuple{CuArrays.CuArray{Float64,3,CuArrays.CuArray{Float64,3,Nothing}},Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArrays.CuArray},Nothing,typeof(abs2),Tuple{CuArrays.CuArray{Float64,3,CuArrays.CuArray{Float64,3,Nothi
ng}}}}}}, ::Tuple{}) at /home/kpamnany/.julia/packages/GPUArrays/1wgPO/src/mapreduce.jl:179
 [11] mapreduce_impl at /home/kpamnany/.julia/packages/GPUArrays/1wgPO/src/mapreduce.jl:75 [inlined]
 [12] #mapreduce#50 at /home/kpamnany/.julia/packages/GPUArrays/1wgPO/src/mapreduce.jl:65 [inlined]
 [13] #mapreduce at ./none:0 [inlined]
 [14] #reduce#196 at ./reduce.jl:357 [inlined]
 [15] (::Base.var"#kw##reduce")(::NamedTuple{(:init, :dims),Tuple{Float64,Colon}}, ::typeof(reduce), ::Function, ::Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArrays.CuArray},Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}},typeof(*),Tuple{CuArrays.CuArray{Float64,3,CuArrays.CuArray{Float64,3,Nothing}},Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArrays.CuArray},Nothing,typeof(abs2),Tuple{C
uArrays.CuArray{Float64,3,CuArrays.CuArray{Float64,3,Nothing}}}}}}) at ./none:0
 [16] weighted_norm_impl(::CuArrays.CuArray{Float64,3,CuArrays.CuArray{Float64,3,Nothing}}, ::CuArrays.CuArray{Float64,3,CuArrays.CuArray{Float64,3,Nothing}}, ::Val{2}, ::Function) at /central/home/kpamnany/CLIMA/src/Arrays/MPIStateArrays.jl:549
 [17] #norm#23(::Function, ::typeof(norm), ::CLIMA.MPIStateArrays.MPIStateArray{Float64,CuArrays.CuArray{Float64,3,Nothing},CuArrays.CuArray{Int64,1,Nothing},CuArrays.CuArray{Float64,3,CuArrays.CuArray{Float64,3,Nothing}},CuArrays.CuArray{Float64,2,Nothing}}, ::Int64, ::Bool) at /central/home/kpamnany/CLIMA/src/Arrays/MPIStateArrays.jl:388
 [18] norm at /central/home/kpamnany/CLIMA/src/Arrays/MPIStateArrays.jl:386 [inlined] (repeats 2 times)
 [19] #invoke!#20(::Tuple{CLIMA.GenericCallbacks.EveryXSimulationSteps}, ::Bool, ::Bool, ::typeof(CLIMA.invoke!), ::CLIMA.SolverConfiguration{Float64}) at /central/home/kpamnany/CLIMA/src/Driver/Driver.jl:339
 [20] (::CLIMA.var"#kw##invoke!")(::NamedTuple{(:user_callbacks, :check_euclidean_distance),Tuple{Tuple{CLIMA.GenericCallbacks.EveryXSimulationSteps},Bool}}, ::typeof(CLIMA.invoke!), ::CLIMA.SolverConfiguration{Float64}) at ./none:0
 [21] main() at /central/home/kpamnany/CLIMA/experiments/GCM/heldsuarez.jl:123
 [22] top-level scope at /central/home/kpamnany/CLIMA/experiments/GCM/heldsuarez.jl:128
 [23] include at ./boot.jl:328 [inlined]
 [24] include_relative(::Module, ::String) at ./loading.jl:1105
 [25] include(::Module, ::String) at ./Base.jl:31
 [26] exec_options(::Base.JLOptions) at ./client.jl:287
 [27] _start() at ./client.jl:460
in expression starting at /central/home/kpamnany/CLIMA/experiments/GCM/heldsuarez.jl:128
caused by [exception 1]
```
Downgrading back to `CuArrays@1.5.0` fixes the problem.

**Comment by simonbyrne** [comment]
I'm happy to drop 1.2 support. Slurm CI now uses 1.3.

**Comment by kpamnany** [comment]
```
julia --color=no --project -e 'using Pkg; pkg"instantiate"; pkg"build"; pkg"precompile"'
ERROR: LoadError: UndefVarError: BinaryPlatforms not defined
```
Cannot replicate interactively. This is for `OpenSpecFun_jll`, which is a dependency of `SpecialFunctions`.

**Comment by kpamnany** [comment]
This is the problem:
```
++ LOADEDMODULES=julia/1.2.0:openmpi/4.0.1
```

Should be solved by https://github.com/climate-machine/slurmci/pull/11.

**Comment by charleskawczynski** [comment]
Thanks for tackling this @kpamnany!

**Comment by kpamnany** [comment]
For `pseudo1D_advection_diffusion.jl`, there is:
```
result[l] ≈ FT(expected_result[dim, l, FT, direction])
   Evaluated: 4.872429f-5 ≈ 4.8848684f-5
```
@simonbyrne: I recall seeing similar errors on the first attempt to move to Julia 1.3 which you had mostly resolved?

**Comment by vchuravy** [comment]
> upgrading to CuArrays@1.7.0 and the associated CUDAdrv and CUDAnative produced:

that sounds like https://github.com/JuliaGPU/CUDAnative.jl/issues/538

can you try CUDAnative v2.9.1?

**Comment by kpamnany** [comment]
bors try

**Comment by kpamnany** [comment]
So it appears that `CuArrays@1.7.0` (and the associated `CUDA`* packages) are breaking `examples/Microphysics/ex_2_Kessler.jl` pretty consistently. 😖 

I've reverted to 1.5.0 and will merge this now as there are dependencies. We can upgrade the CUDA related packages in another PR.

**Comment by kpamnany** [comment]
2 other PRs have merged this morning, maybe the problem is resolved?

**Pull request merged**
