### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by akshaysridhar**
# Description

Specify latest Julia version supported in README file.

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by simonbyrne** [comment]
@akshaysridhar I simplified this a little: feel free to merge if this is okay with you.

**Comment by akshaysridhar** [comment]
> @akshaysridhar I simplified this a little: feel free to merge if this is okay with you.

Thanks @simonbyrne , I've added the relevant changes to the Wiki page as well.

**Pull request merged**
