### PR TITLE
Add fields to moisture aux

### PR DESCRIPTION
**Pull request by charleskawczynski**
Adds variables to moisture aux, broken off from #610

### CODE REVIEW

**Comment by charleskawczynski** [comment]
@simonbyrne ready to merge after review

**Comment by simonbyrne** [comment]
These don't seem to be used anywhere in #610.

@smarras79?

**Comment by smarras79** [comment]
> @simonbyrne ready to merge after review

Is the addition of subsidence to this equation left for a different PR?
The function `flux_moisture` (after appropriate introduction of the subsidence) should include the contribution of the subsidence as below:

```
function flux_moisture!(moist::EquilMoist, flux::Grad, state::Vars, aux::Vars, t::Real)
  ρ = state.ρ
  u = state.ρu / ρ
  z = aux.orientation.Φ / grav
  D = eltype(state)(3.75e-6)
                                                                                                                             
  usub = SVector(0, 0, -D*z)
  flux.moisture.ρq_tot += (u + usub) * state.moisture.ρq_tot
end
```

**Comment by simonbyrne** [comment]
Subsidence is introduced in #609, but these variables aren't used there.

**Comment by charleskawczynski** [comment]
I believe they may be used in diagnostics. I’ll take a look tomorrow to see if they can be computed on the fly, and I can move the definitions over to diagnostics

**Comment by charleskawczynski** [comment]
I believe @simonbyrne is correct, these variables are never actually used, and since they can be computed from a thermo state on the fly in diagnostics, they probably should be if they're needed there.

**Pull request closed without merging**
