### PR TITLE
Symmetric treatment of metrics for 2nd derivatives

### PR DESCRIPTION
**Pull request by jkozdon**
The current way we treat metric terms for 2nd order derivatives is funky. This approach is a little more standard, and respects the symmetry of the operator.

### CODE REVIEW

**Comment by jkozdon** [comment]
bors try

**Comment by lcw** [comment]
As you noted we just need to do this for the vertical kernels as well.

**Comment by jkozdon** [comment]
bors try-

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
> As you noted we just need to do this for the vertical kernels as well.

Thanks! Done.

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try-

**Comment by jkozdon** [comment]
bors try

**Pull request merged**
