### PR TITLE
Move tests and local testing

### PR DESCRIPTION
**Pull request by jkozdon**
- Moves the old `DGBalanceLawDiscretizations` code to `DGmethods_old`
- Add functionality to allow user to run all the slurm tests locally

### CODE REVIEW

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
FYI: @lcw

**Comment by lcw** [comment]
Being able to run slurm jobs locally will be nice!

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try-

**Comment by jkozdon** [comment]
bors try

**Pull request merged**
