### PR TITLE
Add flexibility to how aux is updated

### PR DESCRIPTION
**Pull request by jkozdon**

### CODE REVIEW

**Comment by charleskawczynski** [comment]
What does this do?

**Comment by jkozdon** [comment]
Allows the model to define the logic for updating aux, as opposed to assuming that the aux is always updated the way atmos model needs it updated. Atmos needed integrals and point updates, in the ocean we needed to define some more logic.

**Comment by jkozdon** [comment]
So mainly this adds some flexibility in how aux is updated.

**Pull request merged**
