### PR TITLE
Remove DGmethods_old

### PR DESCRIPTION
**Pull request by jkozdon**

### CODE REVIEW

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
Was surprised to still see these around, might be time for this to go?

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try-

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try-

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try-

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
Realized the microphysics examples used the old balance law framework. @trontrytel Do you still need these?

**Comment by trontrytel** [comment]
> Realized the microphysics examples used the old balance law framework. @trontrytel Do you still need these?

Yes. They have not been moved to the new setup yet.

I'm fine with removing this from master. I have it saved on a separate branch.

**Comment by simonbyrne** [comment]
I think we were waiting on tests to get moved over, see #491.

**Comment by jkozdon** [comment]
Sounds good. Will close this for now then.

**Pull request closed without merging**
