### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by charleskawczynski**
Added a skeleton for the docs.

Right now, there's only a index.md, but I'm hoping that we can start getting used to referencing functions and filling out the documentation as we're developing.

### CODE REVIEW

**Comment by jkozdon** [comment]
This looks good to me. Only suggestion would be to rebase the commits on top of master before accepting it to clean up the git history.

**Comment by jkozdon** [comment]
How will this all work with the subpackages? Does each subpackage have its own docs directory or we just have one docs directory and stuff gets added in there?

**Comment by charleskawczynski** [comment]
> How will this all work with the subpackages? Does each subpackage have its own docs directory or we just have one docs directory and stuff gets added in there?

I don't remember reading anything about deployment of subpackages in the Documenter docs. So, I suspect that there may only be one docs directory. I just asked in the Jula slack Documentation channel.

**Comment by charleskawczynski** [comment]
> Only suggestion would be to rebase the commits on top of master before accepting it to clean up the git history.

I'll do the same with #64.

**Pull request merged**
