### PR TITLE
Split out diffusive and nondiffusive flux terms

### PR DESCRIPTION
**Pull request by jkozdon**
This PR does the following:

 - Cleans up NumericalFluxes.jl a bit
 - Removes old mms_bc_repro file
 - splits flux! into flux_nondiffusive! and flux_diffusive!
 - renames GradNumericalFlux to GradNumericalPenalty
 - Splits numerical flux into a diffusive and nondiffusive part

This is a stepping stone to fixing the boundary condition treatment in the atmos model

### CODE REVIEW

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
@lcw

**Comment by jkozdon** [comment]
bors try-

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
This will need to be updated now that #380 is merged.

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
Assuming the CI passes this should be ready to go now.

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
@simonbyrne Can I merge this?

**Comment by charleskawczynski** [comment]
> @simonbyrne Can I merge this?

Simon is out this week. I'll take a look through now.

**Comment by charleskawczynski** [comment]
Looks good to me.

**Comment by jkozdon** [comment]
bors r!

**Pull request merged**
