### PR TITLE
[TurbConv] update EDMF docs

### PR DESCRIPTION
**Pull request by charleskawczynski**
Fixed and improved reference state equations

### CODE REVIEW

**Comment by charleskawczynski** [comment]
@jkozdon Any idea why what's happening [here](https://codecov.io/gh/climate-machine/CLIMA/pull/210/changes#L47)?

**Comment by jkozdon** [comment]
My guess is that only gets hit if a time step takes long enough. I'm not too worried about it.

**Comment by jkozdon** [comment]
Since we have shortened the test to allow travis to complete, sometimes the run time dependent callbacks don't get hit.

**Comment by jkozdon** [comment]
At least that's my guess.

**Comment by charleskawczynski** [comment]
K, thanks! @simonbyrne feel free to review/merge!

**Comment by charleskawczynski** [comment]
@simonbyrne, ready to go!

**Pull request merged**
