### PR TITLE
Adding documentation to Diagnostics module.

### PR DESCRIPTION
**Pull request by skandalaCLIMA**
# Description

A clear and concise description of the code with usage.

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/format.jl`

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://climate-machine.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by skandalaCLIMA** [comment]
> I can add additional documentation for Diagnostics after you merge this.

Hello Kiran, I believe this piece is ready to be merged.

**Comment by charleskawczynski** [comment]
I'm surprised that this isn't resulting in conflicts, since `CLIMAParameters` has already been added to the docs environment. @kpamnany why is rebase not needed here?

**Comment by kpamnany** [comment]
I haven't a clue @charleskawczynski. bors is currently running CI on a merge of 3 PRs -- is the CLIMAParameters one of them?

**Comment by charleskawczynski** [comment]
CLIMAParameters was to the docs environment in #962. Ah, maybe bors doesn't see a conflict with master yet, if it's still running on the master branch

**Comment by charleskawczynski** [comment]
Strange. @leios any idea what happened here?

**Comment by charleskawczynski** [comment]
For others also confused: @leios pointed out that the bors probably discarded changes already in master during the merge with master, which makes sense.

**Pull request merged**
